package gov.nwcg.isuite.core.persistence.hibernate.query;

import gov.nwcg.isuite.framework.util.LongUtility;


public class CostAccrualReportQuery {

	public static String getCostAccrualSummaryReportQuery(Long extractId, Boolean isOracle) {
		StringBuffer sql = new StringBuffer();

		sql.append("select ")
		   .append(" distinct(acr.rc_line_number) as rcLineNumber ")
		   .append(",rsc.fiscal_year as fiscalYear ")
	       .append(",rsc.account_code as accountingCode ")
	       .append(",acr.rc_line_number as rcLineNumber ")
	       .append(",acr.description as accrualDescription ")
	       //.append(",ir.incident_id as incidentId ")
	       .append(",i.id as incidentId ")
	       .append(",i.incident_name as incidentName ")
	       .append(",i.nbr as incidentNumber ")
	       .append(", (select sum(r.total_amount) from isw_cost_accrual_ext_rsc r ")
	       .append("                             where r.cost_accrual_code = rsc.cost_accrual_code ")
	       .append("                             and r.account_code = rsc.account_code ")
	       .append("                             and r.fiscal_year = rsc.fiscal_year ")
	       .append("                             and cost_accrual_extract_id = " + extractId + " ")
	       .append("  ) as totalAmount ")
	       .append(", (select sum(r.total_amount - r.change_amount) from isw_cost_accrual_ext_rsc r ")
	       .append("                             where r.cost_accrual_code = rsc.cost_accrual_code ")
	        .append("                             and r.account_code = rsc.account_code ")
	       .append("                             and r.fiscal_year = rsc.fiscal_year ")
	       .append("                             and cost_accrual_extract_id = " + extractId + " ")
	       .append("  ) as previousAmount ")
	       .append(", (select sum(r.change_amount) from isw_cost_accrual_ext_rsc r ")
	       .append("                             where r.cost_accrual_code = rsc.cost_accrual_code ")
	        .append("                             and r.account_code = rsc.account_code ")
	       .append("                             and r.fiscal_year = rsc.fiscal_year ")
	       .append("                             and cost_accrual_extract_id = " + extractId + " ") 
	       .append(" ) as changeAmount ")
	       .append("from isw_cost_accrual_ext_rsc rsc ")
	       .append("	, isw_cost_accrual_extract ext ")
	       .append("	, iswl_accrual_code acr ")
	       //.append("	, isw_incident_resource ir ")
	       .append("	, isw_incident i ")
	       .append("where rsc.cost_accrual_extract_id=ext.id ")
	       .append("and ext.id = " + extractId + " ")
	       .append("and acr.code = rsc.cost_accrual_code ")
	       //.append("and rsc.incident_resource_id = ir.id ")
	       //.append("and i.id = ir.incident_id ")
	       .append("and i.id = (select incident_id from isw_incident_account_code where id = rsc.account_code_id ) ")
	       .append("group by ")
	       //.append(" ir.incident_id ")
	       .append(" i.id ")
	       .append(",i.incident_name ")
	       .append(",i.nbr ")
	       .append(",ext.extract_date ")
	       .append(", rsc.fiscal_year ")
	       .append(",rsc.account_code ")
	       .append(",rsc.cost_accrual_code ")
	       .append(",acr.rc_line_number ")
	       .append(",acr.description ")
	       .append(",rsc.total_amount ")
	       .append(",rsc.change_amount ")
	       //.append("order by i.incident_id, rsc.account_code asc ")
	       .append("order by i.id, rsc.account_code asc ")
	       .append(", acr.rc_line_number ")
	       .append(", acr.description ");
		
		return sql.toString();
	}
     
//	public static String getCostAccrualSummaryReportQuery(Long extractId, Long prevExtractId, Boolean isOracle) {
//		StringBuffer sql = new StringBuffer();
//
//		sql.append("select rsc.incident_resource_id as incidentResourceId ")
//	       .append(",ac.account_code as accountingCode")
//	       .append(",acr.rc_line_number as rcLineNumber")
//	       .append(",acr.description as accrualDescription")
//	       .append(",rsc.total_amount as totalAmount");
//		if(LongUtility.hasValue(prevExtractId)){
//			sql.append(",( ")
//		       .append("     select total_amount  ")
//		       .append("     from isw_cost_accrual_ext_rsc rsc2 ")
//		       .append("     where rsc2.cost_accrual_extract_id = " + prevExtractId + " ")
//		       .append("     and rsc2.incident_resource_id = rsc.incident_resource_id ")
//		       .append(" ) as previousAmount ");
//		}else{
//			sql.append(", 0 as previousAmount ");
//		}
//	    sql.append(",rsc.change_amount  as changeAmount ")
//	       .append("from isw_cost_accrual_ext_rsc rsc ")
//	       .append("	, isw_cost_accrual_extract ext ")
//	       .append("	, isw_inc_res_daily_cost dc ")
//	       .append("	, iswl_accrual_code acr ")
//	       .append("	, isw_incident_account_code iac ")
//	       .append("	, isw_account_code ac ")
//	       .append("where rsc.cost_accrual_extract_id=ext.id ")
//	       .append("and ext.id = " + extractId + " ")
//	       .append("and dc.incident_resource_id = rsc.incident_resource_id ")
//	       .append("and iac.id = dc.incident_account_code_id ")
//	       .append("and acr.code = rsc.cost_accrual_code ")
//	       .append("and ac.id = ( ")
//	       .append("	select id from isw_account_code ")
//	       .append("	where id in ( select id from isw_incident_account_code where incident_id = iac.incident_id) ")
//	       .append("	and account_code = (select accrual_account_code from isw_incident_account_code where id = iac.id) ")
//	       .append(") ")
//	       .append("group by rsc.incident_resource_id ")
//	       .append(" , ext.extract_date ")
//	       .append(",ac.account_code ")
//	       .append(",acr.rc_line_number ")
//	       .append(",acr.description ")
//	       .append(",rsc.total_amount ")
//	       .append(",rsc.change_amount ")
//	       .append("order by ac.account_code asc ");
//		
//		return sql.toString();
//	}

	public static String getCostAccrualDetailReportQuery(Long extractId, Boolean isOracle) {
		StringBuffer sql = new StringBuffer();

		sql.append("select rsc.incident_resource_id as incidentResourceId ")
	       .append(", r.is_person as isPerson ")
	       .append(", r.last_name as lastName ")
	       .append(", r.first_name as firstName ")
	       .append(", r.resource_name as resourceName ")
	       .append(", a.request_number as requestNumber ")
	       .append(", case ")
	       .append(" when rsc.draw_down = 'Y' then 'AD PAYMENT' ")
	       .append(" else ")
	       .append(" o.unit_code end as unitCode ")
	       .append(", k.code as itemCode ")
	       .append(", rsc.fiscal_year as fiscalYear ")
	       .append(", rsc.account_code as accountingCode ")
	       .append(", acr.rc_line_number as rcLineNumber ")
	       .append(", acr.description as accrualDescription ")
	       .append(", rsc.total_amount as totalAmount ")
	       .append(", (rsc.total_amount - rsc.change_amount) as previousAmount ")
	       .append(", rsc.change_amount as changeAmount ")
	       //.append(",ir.incident_id as incidentId ")
	       .append(",i.id as incidentId ")
	       .append(",i.incident_name as incidentName ")
	       .append(",i.nbr as incidentNumber ")
	       .append(", (rsc.account_code || rsc.fiscal_year || ' - ' || acr.description) as accountingCodeRcDesc ")
	       .append("from isw_cost_accrual_ext_rsc rsc ")
	       .append(", isw_cost_accrual_extract ext ")
	       .append(", isw_incident_resource ir ")
	       .append(", isw_work_period wp ")
	       .append(", isw_work_period_assignment wpa ")
	       .append(", isw_assignment a ")
	       .append(", iswl_kind k ")
	       .append(", isw_resource r ")
	       .append(", isw_organization o ")
	       .append(", iswl_accrual_code acr ")
	       .append(", isw_incident i ")
	       .append("where rsc.cost_accrual_extract_id=ext.id ")
	       .append("and ext.id = " + extractId + " ")
	       .append("and ir.id = rsc.incident_resource_id ")
	       .append("and rsc.incident_resource_other_id is null ")
	       .append("and r.id = ir.resource_id ")
	       .append("and o.id = R.ORGANIZATION_ID ")
	       .append("and wp.incident_resource_id = ir.id ")
	       .append("and wpa.work_period_id = wp.id ")
	       .append("and a.id = wpa.assignment_id ")
	       .append("and k.id = a.kind_id ")
	       .append("and acr.code = rsc.cost_accrual_code ")
	       .append("and rsc.incident_resource_id = ir.id ")
       //.append("and i.id = ir.incident_id ")
	       .append("and i.id = (select incident_id from isw_incident_account_code where id = rsc.account_code_id ) ")
	       .append("group by i.id ")
	       .append(",i.incident_name ")
	       .append(",i.nbr ")
	       .append(",rsc.incident_resource_id ")
	       .append(",r.resource_name, r.last_name, r.first_name, r.is_person ")
	       .append(" , ext.extract_date ")
	       .append(" ,a.request_number ")
	       .append(" ,o.unit_code ")
	       .append(" ,k.code ")
	       .append(" ,rsc.fiscal_year ")
	       .append(",rsc.account_code ")
	       .append(",acr.rc_line_number ")
	       .append(",acr.description ")
	       .append(",rsc.total_amount ")
	       .append(",rsc.change_amount ")
	       .append(",rsc.draw_down ")
	       .append(" union ")
	       .append("select rsc.incident_resource_other_id as incidentResourceId ")
	       .append(", " + (isOracle ? 0 : false ) + " as isPerson ")
	       .append(", '' as lastName ")
	       .append(", '' as firstName ")
	       .append(", ro.cost_description as resourceName ")
	       .append(", ro.request_number as requestNumber ")
	       .append(", case ")
	       .append(" when rsc.draw_down = 'Y' then 'AD PAYMENT' ")
	       .append(" else ")
	       .append(" 'UNKNOWN' end as unitCode ")
	       .append(", k.code as itemCode ")
	       .append(", rsc.fiscal_year as fiscalYear ")
	       .append(", rsc.account_code as accountingCode ")
	       .append(", acr.rc_line_number as rcLineNumber ")
	       .append(", acr.description as accrualDescription ")
	       .append(", rsc.total_amount as totalAmount ")
	       .append(", (rsc.total_amount - rsc.change_amount) as previousAmount ")
	       .append(", rsc.change_amount as changeAmount ")
	       //.append(",ir.incident_id as incidentId ")
	       .append(",i.id as incidentId ")
	       .append(",i.incident_name as incidentName ")
	       .append(",i.nbr as incidentNumber ")
	       .append(", (rsc.account_code || rsc.fiscal_year || ' - ' || acr.description) as accountingCodeRcDesc ")
	       .append("from isw_cost_accrual_ext_rsc rsc ")
	       .append(", isw_cost_accrual_extract ext ")
	       .append(", isw_incident_resource_other iro ")
	       .append(", iswl_kind k ")
	       .append(", isw_resource_other ro ")
	       .append("     left join isw_organization o on ro.organization_id = o.id ")
	       .append(", iswl_accrual_code acr ")
	       .append(", isw_incident i ")
	       .append("where rsc.cost_accrual_extract_id=ext.id ")
	       .append("and ext.id = " + extractId + " ")
	       .append("and iro.id = rsc.incident_resource_other_id ")
	       .append("and rsc.incident_resource_id is null ")
	       .append("and ro.id = iro.resource_other_id ")
	       .append("and k.id = ro.kind_id ")
	       .append("and acr.code = rsc.cost_accrual_code ")
	       .append("and rsc.incident_resource_other_id = iro.id ")
	       .append("and i.id = (select incident_id from isw_incident_account_code where id = rsc.account_code_id ) ")
	       .append("group by i.id ")
	       .append(",i.incident_name ")
	       .append(",i.nbr ")
	       .append(",rsc.incident_resource_other_id ")
	       .append(",ro.cost_description ")
	       .append(" , ext.extract_date ")
	       .append(" ,ro.request_number ")
	       .append(" ,k.code ")
	       .append(" ,rsc.fiscal_year ")
	       .append(",rsc.account_code ")
	       .append(",acr.rc_line_number ")
	       .append(",acr.description ")
	       .append(",rsc.total_amount ")
	       .append(",rsc.change_amount ")
	       .append(",rsc.draw_down ")
	       .append("order by incidentName, fiscalYear desc")
	       .append(", accountingCode asc ")
	       .append(", accountingCodeRcDesc ")
	       .append(", rcLineNumber ");;
		
		return sql.toString();
	}
	
//	public static String getCostAccrualDetailReportQuery(Long extractId, Long prevExtractId, Boolean isOracle) {
//		StringBuffer sql = new StringBuffer();
//
//		sql.append("select rsc.incident_resource_id as incidentResourceId ")
//	       .append(", r.is_person as isPerson ")
//	       .append(", r.last_name as lastName ")
//	       .append(", r.first_name as firstName ")
//	       .append(", r.resource_name as resourceName ")
//	       .append(",a.request_number as requestNumber ")
//	       .append(", o.unit_code as unitCode ")
//	       .append(", k.code as itemCode ")
//	       .append(",ac.account_code as accountingCode ")
//	       .append(",acr.rc_line_number as rcLineNumber ")
//	       .append(",acr.description as accrualDescription ")
//	       .append(",rsc.total_amount as totalAmount ");
//			if(LongUtility.hasValue(prevExtractId)){
//				sql.append(",( ")
//			       .append("     select total_amount  ")
//			       .append("     from isw_cost_accrual_ext_rsc rsc2 ")
//			       .append("     where rsc2.cost_accrual_extract_id = " + prevExtractId + " ")
//			       .append("     and rsc2.incident_resource_id = rsc.incident_resource_id ")
//			       .append(" ) as previousAmount ");
//			}else{
//				sql.append(", 0 as previousAmount ");
//			}
//	       sql.append(",rsc.change_amount as changeAmount ")
//	       .append("from isw_cost_accrual_ext_rsc rsc ")
//	       .append(", isw_cost_accrual_extract ext ")
//	       .append(", isw_incident_resource ir ")
//	       .append(", isw_work_period wp ")
//	       .append(", isw_work_period_assignment wpa ")
//	       .append(", isw_assignment a ")
//	       .append(", iswl_kind k ")
//	       .append(", isw_resource r ")
//	       .append(", isw_organization o ")
//	       .append(", isw_inc_res_daily_cost dc ")
//	       .append(", iswl_accrual_code acr ")
//	       .append(", isw_incident_account_code iac ")
//	       .append(", isw_account_code ac ")
//	       .append("where rsc.cost_accrual_extract_id=ext.id ")
//	       .append("and ext.id = " + extractId + " ")
//	       .append("and ir.id = rsc.incident_resource_id ")
//	       .append("and r.id = ir.resource_id ")
//	       .append("and o.id = R.ORGANIZATION_ID ")
//	       .append("and wp.incident_resource_id = ir.id ")
//	       .append("and wpa.work_period_id = wp.id ")
//	       .append("and a.id = wpa.assignment_id ")
//	       .append("and k.id = a.kind_id ")
//	       .append("and dc.incident_resource_id = rsc.incident_resource_id ")
//	       .append("and iac.id = dc.incident_account_code_id ")
//	       .append("and acr.code = rsc.cost_accrual_code ")
//	       .append("and ac.id = ( ")
//	       .append("select id from isw_account_code ")
//	       .append("where id in ( select id from isw_incident_account_code where incident_id = iac.incident_id) ")
//	       .append("and account_code = (select accrual_account_code from isw_incident_account_code where id = iac.id) ")
//	       .append(") ") 
//	       .append("group by rsc.incident_resource_id ")
//	       .append(",r.resource_name, r.last_name, r.first_name, r.is_person ")
//	       .append(" , ext.extract_date ")
//	       .append(" ,a.request_number ")
//	       .append(" ,o.unit_code ")
//	       .append(" ,k.code ")
//	       .append(",ac.account_code ")
//	       .append(",acr.rc_line_number ")
//	       .append(",acr.description ")
//	       .append(",rsc.total_amount ")
//	       .append(",rsc.change_amount ")
//	       .append("order by ac.account_code asc ");
//		
//		return sql.toString();
//	}
	
	//public static String getCostAccrualAllDetailReportQuery(Long incidentId, Long incidentGroupId,Boolean isOracle) {
	public static String getCostAccrualAllDetailReportQuery(Long extractId,Boolean isOracle) {
		StringBuffer sql = new StringBuffer();

		sql.append("select rsc.incident_resource_id as incidentResourceId ")
	       .append(", r.is_person as isPerson ")
	       .append(", r.last_name as lastName ")
	       .append(", r.first_name as firstName ")
	       .append(", r.resource_name as resourceName ")
	       .append(",a.request_number as requestNumber ")
	       .append(", o.unit_code as unitCode ")
	       .append(", k.code as itemCode ")
	       .append(",ac.account_code as accountingCode ")
	       .append(",acr.rc_line_number as rcLineNumber ")
	       .append(",acr.description as accrualDescription ")
	       .append(",rsc.total_amount as totalAmount ")
	       .append(", 0 as previousAmount ")
	       .append(",rsc.total_amount as changeAmount ")
	       //.append(",ir.incident_id as incidentId ")
	       .append(",i.id as incidentId ")
	       .append(",i.incident_name as incidentName ")
	       .append(",i.nbr as incidentNumber ")
	       .append("from isw_cost_accrual_ext_rsc rsc ")
	       .append(", isw_cost_accrual_extract ext ")
	       .append(", isw_incident_resource ir ")
	       .append(", isw_work_period wp ")
	       .append(", isw_work_period_assignment wpa ")
	       .append(", isw_assignment a ")
	       .append(", iswl_kind k ")
	       .append(", isw_resource r ")
	       .append(", isw_organization o ")
	       .append(", isw_inc_res_daily_cost dc ")
	       .append(", iswl_accrual_code acr ")
	       .append(", isw_incident_account_code iac ")
	       .append(", isw_account_code ac ")
	       .append(", isw_incident_resource ir ")
	       .append(", isw_incident i ")
	       .append("where rsc.cost_accrual_extract_id=ext.id ")
	       .append("and ext.id = " + extractId + " ")
	       /*
		   if(LongUtility.hasValue(incidentId)){
		       sql.append("and ext.id in (select id from isw_cost_accrual_extract where incident_id = " + incidentId + ") ");
		   }else{
		       sql.append("and ext.id in (select id from isw_cost_accrual_extract where incident_group_id = " + incidentGroupId + ") ");
		   }
		   */
	       .append("and ir.id = rsc.incident_resource_id ")
	       .append("and r.id = ir.resource_id ")
	       .append("and o.id = R.ORGANIZATION_ID ")
	       .append("and wp.incident_resource_id = ir.id ")
	       .append("and wpa.work_period_id = wp.id ")
	       .append("and a.id = wpa.assignment_id ")
	       .append("and k.id = a.kind_id ")
	       .append("and dc.incident_resource_id = rsc.incident_resource_id ")
	       .append("and iac.id = dc.incident_account_code_id ")
	       .append("and acr.code = rsc.cost_accrual_code ")
	       .append("and ac.id = ( ")
	       .append("select id from isw_account_code ")
	       .append("where id in ( select id from isw_incident_account_code where incident_id = iac.incident_id) ")
	       .append("and account_code = (select accrual_account_code from isw_incident_account_code where id = iac.id) ")
	       .append(") ") 
	       .append("and rsc.incident_resource_id = ir.id ")
	       //.append("and i.id = ir.incident_id ")
	       .append("and i.id = (select incident_id from isw_incident_account_code where id = rsc.account_code_id ) ")
	       //.append("group by ir.incident_id ")
	       .append("group by i.id ")
	       .append(",i.incident_name ")
	       .append(",i.nbr ")
	       .append(",rsc.incident_resource_id ")
	       .append(",r.resource_name, r.last_name, r.first_name, r.is_person ")
	       .append(" , ext.extract_date ")
	       .append(" ,a.request_number ")
	       .append(" ,o.unit_code ")
	       .append(" ,k.code ")
	       .append(",ac.account_code ")
	       .append(",acr.rc_line_number ")
	       .append(",acr.description ")
	       .append(",rsc.total_amount ")
	       .append(",rsc.change_amount ")
	       .append("order by ac.account_code asc ");
		
		return sql.toString();
	}
}
