package gov.nwcg.isuite.core.persistence.hibernate.query;

import gov.nwcg.isuite.framework.util.LongUtility;

public class CostResourceDataQuery {

	public static String getResourceCostDataQuery(Long irid,Long incidentId,Long igId, Boolean isOracle){
		StringBuffer sql = new StringBuffer();
		
		sql.append("select distinct(ir.id) as incidentResourceId ")
	       .append(", r.id as resourceId ")
	       .append(", at.id as assignmentTimeId ")
	       .append(", cpi.id as contractorPaymentInfoId ")
	       .append(", cd.id as costDataId ")
	       .append(", a.id as assignmentId ")
	       .append(", cg.id as costGroupId ")
	       .append(", shift.id as shiftId ")
	       .append(", ag.id as agencyId ")
	       .append(", ag.agency_code as agencyCode ")
	       .append(", ag.agency_type as agencyType ")
	       .append(", rg.code as rateGroupType ")
	       .append(", a.assignment_status as status ")
	       .append(", k.id as kindId ")
	       .append(", k.code as kindCode ")
	       .append(", wp.def_incident_account_code_id as defIncidentAccountCodeId ")
	       .append(", ac.account_code as accountCode ")
	       .append(", cd.assign_date as assignDate ")
	       // Defect 5341 remove check on D and R
	       //.append(", case when a.assignment_status in ('D','R') then wp.dm_release_date  ")
	       //.append("       else null ")
	       //.append("  end as releaseDate ")
	       .append(", wp.dm_release_date as releaseDate ")
	       .append(", wp.dm_tentative_arrival_date as arrivalDate ")
	       .append(", cd.is_use_accruals_only as useActualsOnly ");
			if(isOracle == true){
				sql.append(", case ")
				   .append("    when cd.is_generate_costs = 1 then 'true' ")
				   .append("    else 'false' ")
				   .append("  end as generateCostsString ");
			}else{
				sql.append(", case ")
				   .append("    when cd.is_generate_costs = true then 'true' ")
				   .append("    else 'false' ")
				   .append("  end as generateCostsString ");
			}
	       sql.append(", cd.is_generate_costs_sys as generateCostsSysString  ")
	       .append(", df.code as dailyFormCode ")
	       .append(", at.employment_type as employmentType ")
	       .append(", r.parent_resource_id as parentResourceId ")
	       .append(", (select count(r2.id) from isw_resource r2 where r2.parent_resource_id = r.id) as subordinateCount ")
	       .append(", i.cost_default_hours as defaultHours ")
	       .append(", acc.code as accrualCode ")
	       .append(", acc.id as accrualCodeId ")
	       .append(", (select count(atp.id) from isw_assign_time_post atp where atp.assignment_time_id=at.id and atp.deleted_date is null) as timePostCount ")
	       .append(", (select count(taa.id) from isw_time_assign_adjust taa where taa.assignment_id = a.id and taa.deleted_date is null) as adjustmentCount ")
	       .append(", ( ")
           .append(" 	select count(atp2.id) ")
           .append(" 	from isw_assign_time_post atp2 ")
           .append("	, isw_assignment_time at2 ")
           .append("      , isw_assignment a2 ")
           .append("      , isw_work_period_assignment wpa2 ")
           .append("      , isw_work_period wp2 ")
           .append("      , isw_incident_resource ir2 ")
           .append("      , isw_resource r2 ")
           .append(" where atp2.assignment_time_id = at2.id ")
           .append(" and at2.assignment_id = a2.id ")
           .append(" and a2.id = wpa2.assignment_id ")
           .append(" and a2.end_date is null ")
           .append(" and wpa2.work_period_id = wp2.id ")
           .append(" and wp2.incident_resource_id = ir2.id ")
           .append(" and ir2.resource_id = r2.id ")
           .append(" and r2.id in ( ")
           .append("     select id ")
           .append("     from isw_resource r3 where r3.parent_resource_id = r.id ")
           .append(" ) ")
           .append(") as subordinateTimePostCount ")
	       .append(", ( ")
           .append(" 	select count(taa2.id) ")
           .append(" 	from isw_time_assign_adjust taa2 ")
           .append("      , isw_assignment a2 ")
           .append("      , isw_work_period_assignment wpa2 ")
           .append("      , isw_work_period wp2 ")
           .append("      , isw_incident_resource ir2 ")
           .append("      , isw_resource r2 ")
           .append(" where taa2.assignment_id = a2.id ")
           .append(" and a2.id = wpa2.assignment_id ")
           .append(" and a2.end_date is null ")
           .append(" and wpa2.work_period_id = wp2.id ")
           .append(" and wp2.incident_resource_id = ir2.id ")
           .append(" and ir2.resource_id = r2.id ")
           .append(" and r2.id in ( ")
           .append("     select id ")
           .append("     from isw_resource r3 where r3.parent_resource_id = r.id ")
           .append(" ) ")
           .append(") as subordinateTimeAdjustmentCount ")
	       .append(", case ")
           .append("    when rg.code='CONT' then ( ")
           .append("         select irk.rate_type ")
           .append("         from isw_inccost_rate_kind irk ")
           .append("              , isw_inccost_rate icr ")
           .append("         where irk.inccost_rate_id = icr.id ")
           .append("         and icr.incident_id = i.id ")
           .append("         and icr.cost_rate_category='CONTRACTOR' ")                            
           .append("         and irk.kind_id = k.id ")
           .append("   ) ")
           .append("   else 'HOURLY' ")
           .append("  end as contractorRateUom ")
	       .append(", case ")
           .append("    when rg.code='CONT' then ( ")
           .append("         select irk.rate_amount ")
           .append("         from isw_inccost_rate_kind irk ")
           .append("              , isw_inccost_rate icr ")
           .append("         where irk.inccost_rate_id = icr.id ")
           .append("         and icr.incident_id = i.id ")
           .append("         and icr.cost_rate_category='CONTRACTOR' ")                            
           .append("         and irk.kind_id = k.id ")
           .append("   ) ")
           .append("  else 0 ")
           .append("  end as contractorRate ")
           .append(" , case ")
           .append("   when rg.code ='ST' then ( ")
           .append("        select irk.rate_type ")
           .append("        from isw_inccost_rate_kind irk ")
           .append("             , isw_inccost_rate icr ")
           .append("        where irk.inccost_rate_id = icr.id ")
           .append("        and icr.incident_id = i.id ")
           .append("        and icr.cost_rate_category='STATE_COOP' ")                             
           .append("        and irk.kind_id = k.id ")
           .append("   ) ")
           .append("   else 'HOURLY' ")
           .append("   end stateRateUom ")
           .append(" , case ")
           .append("   when rg.code ='ST' then ( ")
           .append("        select irk.rate_amount ")
           .append("        from isw_inccost_rate_kind irk ")
           .append("             , isw_inccost_rate icr ")
           .append("        where irk.inccost_rate_id = icr.id ")
           .append("        and icr.incident_id = i.id ")
           .append("        and icr.cost_rate_category='STATE_COOP' ")                             
           .append("        and irk.kind_id = k.id ")
           .append("   ) ")
           .append("   else 0 ")
           .append("   end stateRate ")
           .append(" , case")
           .append("   when rg.code='FED' then ( ")
           .append("        select irk.rate_type ")
           .append("        from isw_inccost_rate_kind irk ")
           .append("             , isw_inccost_rate icr ")
           .append("        where irk.inccost_rate_id = icr.id ")
           .append("        and icr.incident_id = i.id ")
           .append("        and icr.cost_rate_category='FED' ")                             
           .append("        and irk.kind_id = k.id ")
           .append("   ) ")
           .append("   else 'HOURLY' ")
           .append("end as fedRateUom")
           .append(" , case ")
           .append("   when rg.code ='ST' then ( ")
           .append("        select irk.rate_amount ")
           .append("        from isw_inccost_rate_kind irk ")
           .append("             , isw_inccost_rate icr ")
           .append("        where irk.inccost_rate_id = icr.id ")
           .append("        and icr.incident_id = i.id ")
           .append("        and icr.cost_rate_category='STATE_COOP' ")                             
           .append("        and irk.kind_id = k.id ")
           .append("   ) ")
           .append("   else 0 ")
           .append("   end stateRate ")
           .append(" , case")
           .append("   when rg.code='FED' then ( ")
           .append("        select irk.rate_amount ")
           .append("        from isw_inccost_rate_kind irk ")
           .append("             , isw_inccost_rate icr ")
           .append("        where irk.inccost_rate_id = icr.id ")
           .append("        and icr.incident_id = i.id ")
           .append("        and icr.cost_rate_category='FED' ")                             
           .append("        and irk.kind_id = k.id ")
           .append("   ) ")
           .append("   else 0 ")
           .append("end as fedRate")
           .append(", case ")
           .append("   when (rg.code='ST' and ag.agency_code in ('CNTY','CITY','RUR')) then ( ")
           .append("      select icrsk.rate_amount ")
           .append("      from isw_inccost_rate_state_kind icrsk ")
           .append("           , isw_inccost_rate_state icrs ")
           .append("           ,isw_inccost_rate icr ")
           .append("      where icrsk.inccost_rate_state_id=icrs.id ");
	       if(isOracle==true){
	           sql.append("      and icrs.agency_id = (")
	              .append("        select id from iswl_agency ag5 ")
	              .append("        where ag5.agency_code = substr(org.unit_code,0,2) ")
	              .append("      ) ")
	              .append("");
	       }else{
	           sql.append("      and icrs.agency_id = (")
	              .append("        select id from iswl_agency ag5 ")
	              .append("        where ag5.agency_code = substr(org.unit_code,1,2) ")
	              .append("      ) ")
	              .append("");
	       }
        sql.append("      and icrs.inccost_rate_id = icr.id ")
           .append("      and icr.incident_id = i.id ")
           .append("      and icr.cost_rate_category='STATE_COOP_CUSTOM' ")
           .append("      and icrsk.kind_id = k.id ")           
           .append("  ) ")
           .append("   when rg.code='ST' then ( ")
           .append("      select icrsk.rate_amount ")
           .append("      from isw_inccost_rate_state_kind icrsk ")
           .append("           , isw_inccost_rate_state icrs ")
           .append("           ,isw_inccost_rate icr ")
           .append("      where icrsk.inccost_rate_state_id=icrs.id ")
           .append("      and icrs.agency_id = ag.id ")
           .append("      and icrs.inccost_rate_id = icr.id ")
           .append("      and icr.incident_id = i.id ")
           .append("      and icr.cost_rate_category='STATE_COOP_CUSTOM' ")
           .append("      and icrsk.kind_id = k.id ")           
           .append("  ) ")
           .append("  else 0 ")
           .append(" end stateCustomRate ")
           .append(", case ")
           .append("   when (rg.code='ST' and ag.agency_code in ('CNTY','CITY','RUR')) then ( ")
           .append("      select icrsk.rate_type ")
           .append("      from isw_inccost_rate_state_kind icrsk ")
           .append("           , isw_inccost_rate_state icrs ")
           .append("           ,isw_inccost_rate icr ")
           .append("      where icrsk.inccost_rate_state_id=icrs.id ");
	       if(isOracle==true){
	           sql.append("      and icrs.agency_id = (")
	              .append("        select id from iswl_agency ag5 ")
	              .append("        where ag5.agency_code = substr(org.unit_code,0,2) ")
	              .append("      ) ")
	              .append("");
	       }else{
	           sql.append("      and icrs.agency_id = (")
	              .append("        select id from iswl_agency ag5 ")
	              .append("        where ag5.agency_code = substr(org.unit_code,1,2) ")
	              .append("      ) ")
	              .append("");
	       }
        sql.append("      and icrs.inccost_rate_id = icr.id ")
           .append("      and icr.incident_id = i.id ")
           .append("      and icr.cost_rate_category='STATE_COOP_CUSTOM' ")
           .append("      and icrsk.kind_id = k.id ")           
           .append("  ) ")
           .append("    when rg.code='ST' then ( ")
           .append("      select icrsk.rate_type ")
           .append("      from isw_inccost_rate_state_kind icrsk ")
           .append("          , isw_inccost_rate_state icrs ")
           .append("          ,isw_inccost_rate icr ")
           .append("      where icrsk.inccost_rate_state_id=icrs.id ")
           .append("      and icrs.agency_id = ag.id ")
           .append("      and icrs.inccost_rate_id = icr.id ")
           .append("      and icr.incident_id = i.id ")
           .append("      and icr.cost_rate_category='STATE_COOP_CUSTOM' ")                             
           .append("      and icrsk.kind_id = k.id ")            
           .append(" ) ")
           .append(" else 'HOURLY' ")
           .append("end stateCustomRateUom")
           .append(", case ")
           .append("   when at.employment_type='OTHER' then at.other_default_rate")
           .append("   else 0 ")
           .append(" end as actualOtherRate ")
           .append(", i.incident_end_date as endDate ")
	       .append(", i.incident_start_date as incidentStartDate ")
	       .append("from isw_incident_resource ir ")
	       .append(", isw_incident i ")
	       .append(", isw_cost_data cd ")
	       .append("   left join iswl_accrual_code acc on cd.accrual_code_id = acc.id ")
	       .append(", isw_resource r ")
	       .append("    left join isw_organization org on r.organization_id = org.id ")
	       .append("    left join iswl_agency ag on r.agency_id = ag.id ")
	       .append("    left join iswl_rate_group rg on rg.id = ag.rate_group_id ")
	       .append("    left join isw_cost_group_resource cgr on r.id = cgr.resource_id ")
	       .append("    left join isw_cost_group cg on cgr.cost_group_id = cg.id ")
	       .append("    left join isw_incident_shift shift on cg.incident_shift_id = shift.id ")
	       .append(", isw_work_period wp ")
	       .append("    left join isw_incident_account_code iac on WP.DEF_INCIDENT_ACCOUNT_CODE_ID=iac.id ")
	       .append("    left join isw_account_code ac on iac.account_code_id = ac.id ")
	       .append(", isw_work_period_assignment wpa ")
	       .append(", isw_assignment a ")
	       .append("    left join iswl_kind k on a.kind_id = k.id ")
	       .append("    left join iswl_daily_form df on k.daily_form_id = df.id ")
	       .append("    left join isw_assignment_time at on a.id = at.assignment_id ")
	       .append("    left join isw_contr_payment_info cpi on at.id = cpi.assignment_time_id ");
			if(LongUtility.hasValue(irid)){
				sql.append("where ir.incident_id in ( select incident_id from isw_incident_resource where id = " + irid + ") ");
			}else{
				if(LongUtility.hasValue(incidentId))
					sql.append("where ir.incident_id = " + incidentId + " ");
				else
					sql.append("where ir.incident_id in (select incident_id from isw_incident_group_incident where incident_group_id = " + igId + ") ");
			}
	    sql.append("and i.id = ir.incident_id ")
	       .append("and cd.id = ir.cost_data_id ")
	       .append("and r.id = ir.resource_id ")
	       .append("and wp.incident_resource_id = ir.id ")
	       .append("and wpa.work_period_id = wp.id ")
	       .append("and a.id = wpa.assignment_id ")
	       .append("and a.end_date is null ");
		
		return sql.toString();
	}

	public static String getResourceOtherCostDataQuery(Long iroid,Long incidentId ,Long igId, Boolean isOracle){
		StringBuffer sql = new StringBuffer();
		sql
		.append("select iro.id as incidentResourceOtherId ")
		.append("   , ro.id as resourceOtherId ")
	    .append("   , cd.id as costDataId ")
	    .append("   , cd.assign_date as assignDate ")
	    .append("	, cd.accrual_code_id as accrualCodeId ");
		if(isOracle == true){
			sql.append(", case ")
			   .append("    when cd.is_generate_costs = 1 then 'true' ")
			   .append("    else 'false' ")
			   .append("  end as generateCostsString ");
		}else{
			sql.append(", case ")
			   .append("    when cd.is_generate_costs = true then 'true' ")
			   .append("    else 'false' ")
			   .append("  end as generateCostsString ");
		}
	    sql.append("   , iro.resource_other_id as resourceOtherId ")
	    .append("   , i.cost_default_hours as defaultHours")
	    .append("   , k.id as kindId ")
	    .append("   , k.code as kindCode ")
	    .append("   , ag.id as agencyId ")
	    .append("   , ag.agency_code as agencyCode ")
	    .append("   , ag.agency_type as agencyType ")
        .append("	, rg.code as rateGroupType ")
	    .append("   , iac.id as defIncidentAccountCodeId ")
        .append(" , ro.actual_release_date as releaseDate ")
        //.append(", case when iro.assignment_status in ('D','R') then ro.actual_release_date  ")
        //.append("       else null ")
        //.append("  end as releaseDate ")
	    //.append("   , ro.actual_release_date as releaseDate ")
	    .append("   , case ")
	    .append("        when rg.code = 'FED' then ( ")
	    .append("                    select irk.rate_amount ")
	    .append("                    from isw_inccost_rate_kind irk ")
	    .append("                         , isw_inccost_rate icr ")
	    .append("                    where irk.inccost_rate_id = icr.id ")
	    .append("                    and icr.incident_id = i.id ")
	    .append("                    and icr.cost_rate_category='FED' ")                            
	    .append("                    and irk.kind_id = k.id ")
	    .append("        ) ")
	    .append("      else 0 ")
	    .append("  end as fedRate ")
	    .append("   , case ")
	    .append("        when rg.code = 'FED' then ( ")
	    .append("                    select irk.rate_type ")
	    .append("                    from isw_inccost_rate_kind irk ")
	    .append("                         , isw_inccost_rate icr ")
	    .append("                    where irk.inccost_rate_id = icr.id ")
	    .append("                    and icr.incident_id = i.id ")
	    .append("                    and icr.cost_rate_category='FED' ")                            
	    .append("                    and irk.kind_id = k.id ")
	    .append("        ) ")
	    .append("      else 'HOURLY' ")
	    .append("  end as fedRateUom ")
	    .append("   , case ")
	    .append("        when rg.code = 'CONT' then ( ")
	    .append("                    select irk.rate_amount ")
	    .append("                    from isw_inccost_rate_kind irk ")
	    .append("                         , isw_inccost_rate icr ")
	    .append("                    where irk.inccost_rate_id = icr.id ")
	    .append("                    and icr.incident_id = i.id ")
	    .append("                    and icr.cost_rate_category='CONTRACTOR' ")                            
	    .append("                    and irk.kind_id = k.id ")
	    .append("        ) ")
	    .append("      else 0 ")
	    .append("  end as contractorRate ")
	    .append("   , case ")
	    .append("        when rg.code = 'CONT' then ( ")
	    .append("                    select irk.rate_type ")
	    .append("                    from isw_inccost_rate_kind irk ")
	    .append("                         , isw_inccost_rate icr ")
	    .append("                    where irk.inccost_rate_id = icr.id ")
	    .append("                    and icr.incident_id = i.id ")
	    .append("                    and icr.cost_rate_category='CONTRACTOR' ")                            
	    .append("                    and irk.kind_id = k.id ")
	    .append("        ) ")
	    .append("      else 'HOURLY' ")
	    .append("  end as contractorRateUom ")
	    .append("   , case ")
	    .append("        when rg.code = 'ST' then ( ")
	    .append("                    select irk.rate_amount ")
	    .append("                    from isw_inccost_rate_kind irk ")
	    .append("                         , isw_inccost_rate icr ")
	    .append("                    where irk.inccost_rate_id = icr.id ")
	    .append("                    and icr.incident_id = i.id ")
	    .append("                    and icr.cost_rate_category='STATE_COOP' ")                            
	    .append("                    and irk.kind_id = k.id ")
	    .append("        ) ")
	    .append("      else 0 ")
	    .append("  end as stateRate ")
	    .append("   , case ")
	    .append("        when rg.code = 'ST' then ( ")
	    .append("                    select irk.rate_type ")
	    .append("                    from isw_inccost_rate_kind irk ")
	    .append("                         , isw_inccost_rate icr ")
	    .append("                    where irk.inccost_rate_id = icr.id ")
	    .append("                    and icr.incident_id = i.id ")
	    .append("                    and icr.cost_rate_category='STATE_COOP' ")                            
	    .append("                    and irk.kind_id = k.id ")
	    .append("        ) ")
	    .append("      else 'HOURLY' ")
	    .append("  end as stateRateUom ")
	    .append("   , case ")
	    .append("        when rg.code = 'ST' then ( ")
	    .append("                    select irk.rate_amount ")
	    .append("                    from isw_inccost_rate_kind irk ")
	    .append("                         , isw_inccost_rate icr ")
	    .append("                    where irk.inccost_rate_id = icr.id ")
	    .append("                    and icr.incident_id = i.id ")
	    .append("                    and icr.cost_rate_category='STATE_COOP_CUSTOM' ")                            
	    .append("                    and irk.kind_id = k.id ")
	    .append("        ) ")
	    .append("      else 0 ")
	    .append("  end as stateCustomRate ")
	    .append("   , case ")
	    .append("        when rg.code = 'ST' then ( ")
	    .append("                    select irk.rate_type ")
	    .append("                    from isw_inccost_rate_kind irk ")
	    .append("                         , isw_inccost_rate icr ")
	    .append("                    where irk.inccost_rate_id = icr.id ")
	    .append("                    and icr.incident_id = i.id ")
	    .append("                    and icr.cost_rate_category='STATE_COOP_CUSTOM' ")                            
	    .append("                    and irk.kind_id = k.id ")
	    .append("        ) ")
	    .append("      else 'HOURLY' ")
	    .append("  end as stateCustomRateUom ")
        .append(", i.incident_end_date as endDate ")
        .append(", i.incident_start_date as incidentStartDate ")
	    .append("from isw_incident_resource_other iro ")
	    .append("    left join isw_cost_data cd on iro.cost_data_id = cd.id ")
	    .append(" , isw_incident i ")
	    .append(" , isw_resource_other ro ")
	    .append("     left join iswl_kind k on ro.kind_id = k.id ")
	    .append("     left join iswl_agency ag on ro.agency_id = ag.id ")
        .append("    left join iswl_rate_group rg on rg.id = ag.rate_group_id ")
	    .append("     left join isw_incident_account_code iac on ro.incident_account_code_id = iac.id ");
		if(LongUtility.hasValue(iroid)){
			sql.append("where iro.incident_id in ( select incident_id from isw_incident_resource_other where id = " + iroid + ") ");
		}else{
			if(LongUtility.hasValue(incidentId))
				sql.append("where iro.incident_id = " + incidentId + " ");
			else
				sql.append("where iro.incident_id in (select incident_id from isw_incident_group_incident where incident_group_id = " + igId + ") ");
		}
	    sql.append("and i.id = iro.incident_id ")
	    .append("and ro.id = iro.resource_other_id ");
		
		return sql.toString();
	}
	
}
