package gov.nwcg.isuite.core.persistence.hibernate.query;


public class IapDefaultSettingsQuery {
	
	public static enum _203Settings {

		//SECTION: INCIDENT_COMMANDER
		INC_COMMANDER1("INCIDENT_COMMANDER", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
					   "SELECT :seqId, :incidentId, '203', 'IC/UC', 'INCIDENT_COMMANDER', K.id " +
					   "FROM ISWL_KIND K WHERE CODE IN ('ICT1','ICT2','ICT3','ICT4','ICT5','DPIC') ")
		,INC_COMMANDER2("INCIDENT_COMMANDER", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
					   "SELECT :seqId, :incidentId, '203', 'DEPUTY', 'INCIDENT_COMMANDER', K.id " +
					   "FROM ISWL_KIND K WHERE CODE IN ('DPIC','ICT1','ICT2','ICT3','ICT4','ICT5') ")
		,SAFETY_OFFICER("INCIDENT_COMMANDER", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				        "SELECT :seqId, :incidentId, '203', 'SAFETY OFFICER', 'INCIDENT_COMMANDER', K.id " +
				        "FROM ISWL_KIND K WHERE CODE IN ('SOF1','SOF2','SOFR') ")
	    ,INFO_OFFICER("INCIDENT_COMMANDER", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
	    		      "SELECT :seqId, :incidentId, '203', 'INFORMATION OFFICER', 'INCIDENT_COMMANDER', K.id " +
	    		      "FROM ISWL_KIND K WHERE CODE IN ('PIO1','PIO2','PIOF') ")
	    ,LIAISON_OFFICER("INCIDENT_COMMANDER", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
	    		        "SELECT :seqId, :incidentId, '203', 'LIAISON OFFICER', 'INCIDENT_COMMANDER', K.id " +
	    		        "FROM ISWL_KIND K WHERE CODE IN ('LOFR') " )

		//SECTION: PLANNING_SECTION
	   ,PLANNING_CHIEF("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			  "SELECT :seqId, :incidentId, '203', 'CHIEF', 'PLANNING_SECTION', K.id " +
			  "FROM ISWL_KIND K WHERE CODE IN ('PSC1','PSC2') ")
	   ,PLANNING_DEPUTY("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   "SELECT :seqId, :incidentId, '203', 'DEPUTY', 'PLANNING_SECTION', K.id " +
			   "FROM ISWL_KIND K WHERE CODE IN ('PSC1','PSC2') ")
	   ,RES_UNIT_LEADER("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			            "SELECT :seqId, :incidentId, '203', 'RESOURCES UNIT', 'PLANNING_SECTION', K.id " +
			            "FROM ISWL_KIND K WHERE CODE IN ('RESL') " )
	   ,SIT_UNIT_LEADER("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   	  		"SELECT :seqId, :incidentId, '203', 'SITUATION UNIT', 'PLANNING_SECTION', K.id " +
			   	  		"FROM ISWL_KIND K WHERE CODE IN ('SITL') ")
	   ,DOCUMEN_UNIT("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   		"SELECT :seqId, :incidentId, '203', 'DOCUMENTATION UNIT', 'PLANNING_SECTION', K.id " +
	   				"FROM ISWL_KIND K WHERE CODE IN ('DOCL') " )
	   ,DEMOB_UNIT("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   		"SELECT :seqId, :incidentId, '203', 'DEMOBILIZATION UNIT', 'PLANNING_SECTION', K.id " +
	   				"FROM ISWL_KIND K WHERE CODE IN ('DMOB') " )
	   ,FIRE_BEHAV_ANLYST("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
					"SELECT :seqId, :incidentId, '203', 'FIRE BEHAVIOR ANALYST', 'PLANNING_SECTION', K.id " +
					"FROM ISWL_KIND K WHERE CODE IN ('FBAN') " )
	   ,HR_SPECIALIST("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   		"SELECT :seqId, :incidentId, '203', 'HUMAN RESOURCE SPECIALIST', 'PLANNING_SECTION', K.id " +
	   				"FROM ISWL_KIND K WHERE CODE IN ('HRSP') " )
	   ,TRN_SPECIALIST("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   		"SELECT :seqId, :incidentId, '203', 'TRAINING SPECIALIST', 'PLANNING_SECTION', K.id " +
	   				"FROM ISWL_KIND K WHERE CODE IN ('TNSP') " )
	   ,GIS_SPECIALIST("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   		"SELECT :seqId, :incidentId, '203', 'GIS SPECIALIST', 'PLANNING_SECTION', K.id " +
	   				"FROM ISWL_KIND K WHERE CODE IN ('GISS') " )
	   ,TECHNOLOGY_SUPPORT_SPECIALIST("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   		"SELECT :seqId, :incidentId, '203', 'TECHNOLOGY SUPPORT SPECIALIST', 'PLANNING_SECTION', K.id " +
	   				"FROM ISWL_KIND K WHERE CODE IN ('ITSS') " )
	   ,INC_METEOROLOGIST("PLANNING_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   		"SELECT :seqId, :incidentId, '203', 'INCIDENT METEOROLOGIST', 'PLANNING_SECTION', K.id " +
	   				"FROM ISWL_KIND K WHERE CODE IN ('IMET') " )
		
		//SECTION: LOGISTICS_SECTION
	   ,LOGISTICS_CHIEF("LOGISTICS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   		"SELECT :seqId, :incidentId, '203', 'CHIEF', 'LOGISTICS_SECTION', K.id " +
	   				"FROM ISWL_KIND K WHERE CODE IN ('LSC1','LSC2') " )
	   ,LOGISTICS_DEPUTY("LOGISTICS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   	"SELECT :seqId, :incidentId, '203', 'DEPUTY', 'LOGISTICS_SECTION', K.id " +
	   			"FROM ISWL_KIND K WHERE CODE IN ('LSC1','LSC2') " )
	   ,SUPPLY_UNIT_LEADER("LOGISTICS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   	"SELECT :seqId, :incidentId, '203', 'SUPPLY UNIT', 'LOGISTICS_SECTION', K.id " +
	   			"FROM ISWL_KIND K WHERE CODE IN ('SPUL') " )
	   ,FACILITIES_UNIT_LEADER("LOGISTICS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   	"SELECT :seqId, :incidentId, '203', 'FACILITIES UNIT', 'LOGISTICS_SECTION', K.id " +
	   			"FROM ISWL_KIND K WHERE CODE IN ('FACL') " )
	   ,GROUND_SUPPORT_UNIT_LEADER("LOGISTICS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   "SELECT :seqId, :incidentId, '203', 'GROUND SUPPORT UNIT', 'LOGISTICS_SECTION', K.id " +
	   			"FROM ISWL_KIND K WHERE CODE IN ('GSUL') " )
	   ,COMM_UNIT_LEADER("LOGISTICS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   	"SELECT :seqId, :incidentId, '203', 'COMMUNICATIONS UNIT', 'LOGISTICS_SECTION', K.id " +
	   			"FROM ISWL_KIND K WHERE CODE IN ('COML') " )
	   ,MEDICAL_UNIT_LEADER("LOGISTICS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
			   	"SELECT :seqId, :incidentId, '203', 'MEDICAL UNIT', 'LOGISTICS_SECTION', K.id " +
	   			"FROM ISWL_KIND K WHERE CODE IN ('MEDL') " )
	   ,SECURITY_UNIT_LEADER("LOGISTICS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'SECURITY UNIT', 'LOGISTICS_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('SECM','SEC1','SEC2') " ) 
	   ,FOOD_UNIT_LEADER("LOGISTICS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'FOOD UNIT', 'LOGISTICS_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('FDUL') " )
		
		//SECTION: OPERATIONS_SECTION
		,DAY("OPERATIONS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'DAY OPS SECTION CHIEF', 'OPERATIONS_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('OSC1','OSC2','OPBD') " )
		,NIGHT("OPERATIONS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'NIGHT OPS SECTION CHIEF', 'OPERATIONS_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('OSC1','OSC2','OPBD') " )
		,OPERATIONS_PLANNING("OPERATIONS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'PLANNING OPS', 'OPERATIONS_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('OSC1','OSC2','OPBD') " )
		,OPERATIONS_CHIEF("OPERATIONS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'OPS SECTION CHIEF', 'OPERATIONS_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('OSC1','OSC2','OPBD') " )
		,OPERATIONS_DEPUTY("OPERATIONS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'DEPUTY OPS SECTION CHIEF', 'OPERATIONS_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('OSC1','OSC2','OPBD') " )
		,STAGING_AREA("OPERATIONS_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'STAGING AREA', 'OPERATIONS_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('STAM') " )
		
		//SECTION: FINANCE_SECTION
		,FINANCE_CHIEF("FINANCE_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'CHIEF', 'FINANCE_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('FSC1','FSC2') " )
		,FINANCE_DEPUTY("FINANCE_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'DEPUTY', 'FINANCE_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('FSC1','FSC2') " )
		,TIME_UNIT("FINANCE_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'TIME UNIT', 'FINANCE_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('TIME') " )
		,PROCUREMENT("FINANCE_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'PROCUREMENT UNIT', 'FINANCE_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('PROC') " )
		,COMPENSATION("FINANCE_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'COMPENSATION UNIT', 'FINANCE_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('COMP') " )
		,COST_UNIT("FINANCE_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'COST UNIT', 'FINANCE_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('COST') " )
		
		//SECTION: AGENCY_REP
		,AGENCY_REP("AGENCY_REP", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'AGENCY REP', 'AGENCY_REP', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('AREP') " )
		
		//SECTION: BRANCH_SECTION
		,BRANCH_DIRECTOR("BRANCH_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'BRANCH DIRECTOR', 'BRANCH_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('OPBD','DIVS','OSC1','OSC2') " )
		,BRANCH_DEPUTY("BRANCH_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'DEPUTY', 'BRANCH_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('OPBD','DIVS','OSC1','OSC2') " )
		,DIVISION_GROUP("BRANCH_SECTION", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'DIVISION/GROUP', 'BRANCH_SECTION', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('DIVS') " )
				
		//SECTION: AIR_OPS_SECTION
		,AIR_OPS_BRANCH_DIRECTOR("AIR_OPERATIONS", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'AIR OPS BRANCH DIRECTOR', 'AIR_OPERATIONS', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('AOBD','ASGS') " )
		,AIR_ATTACK_SUPERVISOR("AIR_OPERATIONS", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'AIR ATTACK SUPERVISOR', 'AIR_OPERATIONS', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('ATGS') " )
		,AIR_SUPPORT_SUPERVISOR("AIR_OPERATIONS", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'AIR SUPPORT SUPERVISOR', 'AIR_OPERATIONS', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('ASGS') " )
		,HELICOPTER_COORDINATOR("AIR_OPERATIONS", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'HELICOPTER COORDINATOR', 'AIR_OPERATIONS', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('HLCO') " )
		,AIR_TANKER_COORDINATOR("AIR_OPERATIONS", "INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
				"SELECT :seqId, :incidentId, '203', 'AIR TANKER COORDINATOR', 'AIR_OPERATIONS', K.id " +
				"FROM ISWL_KIND K WHERE CODE IN ('ATCO') " )
				
		;

		public String section = "";
		public String sql = "";
		
		_203Settings(String section, String sql){
			this.section = section;
			this.sql=sql;
		}
	}

	public static enum _204Settings {
		OPERATIONS_CHIEF("INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
					   "SELECT :seqId, :incidentId, '204', 'OPERATIONS CHIEF', 'OPERATIONS_PERSONNEL', K.id " +
					   "FROM ISWL_KIND K WHERE CODE IN ('OSC1','OSC2','OPBD') ")
		,BRANCH_DIRECTOR("INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
					   "SELECT :seqId, :incidentId, '204', 'BRANCH DIRECTOR', 'OPERATIONS_PERSONNEL', K.id " +
					   "FROM ISWL_KIND K WHERE CODE IN ('OSC1','OSC2','OPBD','DIVS') ")
		,DIVISIONGROUP_SUPERVISOR("INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
					   "SELECT :seqId, :incidentId, '204', 'DIVISION/GROUP SUPERVISOR', 'OPERATIONS_PERSONNEL', K.id " +
					   "FROM ISWL_KIND K WHERE CODE IN ('DIVS') ")
		,AIRATTACK_SUPERVISOR("INSERT INTO ISW_IAP_POSITION_ITEM_CODE (ID, :fieldName, FORM, POSITION, SECTION, KIND_ID) " +
					   "SELECT :seqId, :incidentId, '204', 'AIR ATTACK SUPERVISOR', 'OPERATIONS_PERSONNEL', K.id " +
					   "FROM ISWL_KIND K WHERE CODE IN ('AOBD','ATGS') ")
		;

		public String sql = "";
		
		_204Settings(String sql){
			this.sql=sql;
		}
	}

	public static enum _203BranchSettings {
		BRANCH_DIRECTOR("INSERT INTO ISW_BRANCH_SETTING_POSITION (ID, BRANCH_SETTING_ID, POSITION, KIND_ID) " +
					   "SELECT :seqId, :branchSettingId, 'BRANCH DIRECTOR', K.id " +
					   "FROM ISWL_KIND K WHERE CODE IN ('OSC1','OSC2','OPBD','DIVS') ")
		,DEPUTY("INSERT INTO ISW_BRANCH_SETTING_POSITION (ID, BRANCH_SETTING_ID, POSITION, KIND_ID) " +
					   "SELECT :seqId, :branchSettingId, 'DEPUTY', K.id " +
					   "FROM ISWL_KIND K WHERE CODE IN ('OSC1','OSC2','OPBD','DIVS') ")
		,DIVISION_GROUP("INSERT INTO ISW_BRANCH_SETTING_POSITION (ID, BRANCH_SETTING_ID, POSITION, KIND_ID) " +
					   "SELECT :seqId, :branchSettingId, 'DIVISION/GROUP', K.id " +
					   "FROM ISWL_KIND K WHERE CODE IN ('DIVS') ")
		;

		public String sql = "";
		
		_203BranchSettings(String sql){
			this.sql=sql;
		}
	}
}
