UPDATE ISW_IAP_POSITION_ITEM_CODE SET POSITION = 'TECHNOLOGY SUPPORT SPECIALIST' WHERE POSITION = 'COMPUTER SPECIALIST';
UPDATE ISW_IAP_POSITION_ITEM_CODE SET KIND_ID = (SELECT ID FROM ISWL_KIND WHERE CODE = 'ITSS') WHERE KIND_ID = (SELECT ID FROM ISWL_KIND WHERE CODE = 'CTSP');
INSERT INTO SCHEMACHANGELOG( ID, MAJORRELEASENUMBER, MINORRELEASENUMBER, POINTRELEASENUMBER, SCRIPTNAME, DATEAPPLIED)
VALUES (242,'01','02','01.00','patch.242.sc-pg.01_02_01.00.sql', now());
UPDATE REVISION SET REVISIONLEVEL = 242;
