ALTER TABLE ISW_INCIDENT_RESOURCE ADD RES_NUM_ID BIGINT DEFAULT 0
/
CREATE OR REPLACE FUNCTION update_res_num(p_incident_resource_id BIGINT )
  RETURNS BIGINT
  LANGUAGE plpgsql
AS
$body$
DECLARE
  v_rnum_id BIGINT;
BEGIN
  SELECT RES_NUM_ID
  INTO v_rnum_id
  FROM ISW_INCIDENT_RESOURCE
  WHERE INCIDENT_ID =
    (SELECT INCIDENT_ID
    FROM ISW_INCIDENT_RESOURCE
    WHERE ID = p_incident_resource_id
    );
  IF v_rnum_id > 0 THEN
    RETURN v_rnum_id;
  ELSE
    SELECT MAX(RES_NUM_ID)
    INTO v_rnum_id
    FROM ISW_INCIDENT_RESOURCE
    WHERE INCIDENT_ID =
      (SELECT INCIDENT_ID
      FROM ISW_INCIDENT_RESOURCE
      WHERE ID = p_incident_resource_id
      );
    UPDATE ISW_INCIDENT_RESOURCE
    SET res_num_id = v_rnum_id + 1
    WHERE ID       = p_incident_resource_id;
    RETURN v_rnum_id + 1;
  END IF;
END;
$body$
/
INSERT INTO SCHEMACHANGELOG( ID, MAJORRELEASENUMBER, MINORRELEASENUMBER, POINTRELEASENUMBER, SCRIPTNAME, DATEAPPLIED)
VALUES (229,'00','03','04.03','patch.229.sc-pg.00_03_04.03.sql', now())
/
UPDATE REVISION SET REVISIONLEVEL = 229
/
