INSERT INTO ISWL_CUSTOM_REPORT_VIEW (ID, VIEW_NAME, VIEW_CODE, DISPLAY_NAME)
VALUES (nextVal('SEQ_CUSTOM_REPORT_VIEW'), 'ISWV_CR_TNSP_TRAIN_EVAL', 'TNSP_TRAIN_EVAL_VIEW','TRAINEE DATA');
INSERT INTO ISW_CUSTOM_REPORT_VIEW_ROLE (VIEW_ID, ROLE_ID) VALUES ((SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), (SELECT ID FROM ISW_SYSTEM_ROLE WHERE ROLE_NAME = 'ROLE_TRAINING_SPECIALIST'));
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'ACTUAL_RELEASE_DATE', 'ACTUAL RELEASE DATE', 'DATE', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'ACTUAL_RELEASE_TIME', 'ACTUAL RELEASE TIME', 'TIME', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'AGENCY', 'AGENCY', 'STRING', 'AGENCY');
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'CELLPHONE', 'CELLPHONE', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'CHECK_IN_DATE', 'CHECK IN DATE', 'DATE', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'CHECK_IN_TIME', 'CHECK IN TIME', 'TIME', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'DEMOBILIZATION_CITY', 'DEMOBILIZATION CITY', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'DEMOBILIZATION_DATE', 'DEMOBILIZATION DATE', 'DATE', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'DEMOBILIZATION_STATE', 'DEMOBILIZATION STATE', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EMPLOYMENT_TYPE', 'EMPLOYMENT TYPE', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'FIRST_DAY_OF_WORK', 'FIRST DAY OF WORK', 'DATE', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'TRAINEE_FIRST_NAME', 'TRAINEE FIRST NAME', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'INCIDENT_NAME', 'INCIDENT NAME', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'INCIDENT_NUMBER', 'INCIDENT NUMBER', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'ITEM_CODE', 'ITEM CODE', 'STRING',  'ITEM_CODE');
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'ITEM_CODE_DESCRIPTION', 'ITEM CODE DESCRIPTION', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'TRAINEE_LAST_NAME', 'TRAINEE LAST NAME', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'LENGTH_OF_ASSIGNMENT', 'LENGTH OF ASSIGNMENT', 'NUMBER', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'LINE_OVERHEAD', 'LINE OVERHEAD', 'BOOLEAN', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'MOBILIZATION_DATE', 'MOBILIZATION DATE', 'DATE', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'OTHER1', 'OTHER1', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'OTHER2', 'OTHER2', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'OTHER3', 'OTHER3', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'PARENT_ID', 'PARENT ID', 'NUMBER', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'REMARKS_PLANS', 'REMARKS PLANS', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'TRAINEE_REQUEST_NUMBER', 'TRAINEE REQUEST NUMBER', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'RESOURCE_ID', 'RESOURCE ID', 'NUMBER', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'RESOURCE_LEVEL', 'RESOURCE LEVEL', 'NUMBER', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'TRAINEE_RESOURCE_NAME', 'TRAINEE RESOURCE NAME', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'RETURN_METHOD_OF_TRAVEL', 'RETURN METHOD OF TRAVEL', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'SECTION_CODE', 'SECTION CODE', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'SECTION_DESCRIPTION', 'SECTION DESCRIPTION', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'STATUS', 'STATUS', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'TENTATIVE_RELEASE_DATE', 'TENTATIVE RELEASE DATE', 'DATE', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'TENTATIVE_RELEASE_TIME', 'TENTATIVE RELEASE TIME', 'TIME', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'TRAINEE', 'TRAINEE CHECKBOX', 'BOOLEAN', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'ASSIGNMENT_ACRES', 'ASSIGNMENT ACRES', 'NUMBER', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'ASSIGNMENT_COMPLEXITY', 'ASSIGNMENT COMPLEXITY', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'ASSIGNMENT_END_DATE', 'ASSIGNMENT END DATE', 'DATE', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'ASSIGNMENT_ITEM_CODE', 'ASSIGNMENT ITEM CODE', 'STRING', 'ITEM_CODE');
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'ASSIGNMENT_ITEM_CODE_DESC', 'ASSIGNMENT ITEM CODE DESCRIPTION', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'ASSIGNMENT_START_DATE', 'ASSIGNMENT START DATE', 'DATE', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'CURRENT_HOME_UNIT_TASKBOOK', 'CURRENT HOME UNIT TASKBOOK', 'BOOLEAN', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_REQUEST_NUMBER', 'EVALUATOR REQUEST NUMBER', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES 
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_INCIDENT', 'EVALUATOR INCIDENT', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_ITEM_CODE', 'EVALUATOR ITEM CODE', 'STRING', 'ITEM_CODE');
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_ITEM_CODE_DESC', 'EVALUATOR ITEM CODE DESCRIPTION', 'STRING',  NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_STATUS', 'EVALUATOR STATUS', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_UNIT_ID', 'EVALUATOR UNIT ID', 'STRING', 'UNIT_ID');
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_UNIT_ID_DESC', 'EVALUATOR UNIT ID DESCRIPTION', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_NON_INCIDENT', 'EVALUATOR NON INCIDENT', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_ADDRESS', 'EVALUATOR ADDRESS', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_CITY', 'EVALUATOR CITY', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_STATE', 'EVALUATOR STATE', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_ZIP', 'EVALUATOR ZIP', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_PHONE', 'EVALUATOR PHONE', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'EVALUATOR_EMAIL', 'EVALUATOR EMAIL', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'HOME_UNIT_CONTACT_NAME', 'HOME UNIT CONTACT NAME', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'HOME_UNIT_CONTACT_UNIT_ID', 'HOME UNIT CONTACT UNIT ID', 'STRING', 'UNIT_ID');
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'HOME_UNIT_CONTACT_UNIT_ID_DESC', 'HOME UNIT CONTACT UNIT ID DESCRIPTION', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'HOME_UNIT_CONTACT_ADDRESS', 'HOME UNIT CONTACT ADDRESS', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'HOME_UNIT_CONTACT_CITY', 'HOME UNIT CONTACT CITY', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'HOME_UNIT_CONTACT_STATE', 'HOME UNIT CONTACT STATE', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'HOME_UNIT_CONTACT_ZIP', 'HOME UNIT CONTACT ZIP', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'HOME_UNIT_CONTACT_PHONE', 'HOME UNIT CONTACT PHONE', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'HOME_UNIT_CONTACT_EMAIL', 'HOME UNIT CONTACT EMAIL', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'INCIDENT_ISSUED_TASKBOOK', 'INCIDENT ISSUED TASKBOOK', 'BOOLEAN', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'INITIAL_ASSIGNMENT', 'INITIAL ASSIGNMENT', 'BOOLEAN', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'LENGTH_OF_TRAINEE_ASSIGNMENT', 'LENGTH OF TRAINEE ASSIGNMENT', 'NUMBER', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'REDCARD_ASSIGNMENT_CERT', 'REDCARD ASSIGNMENT CERTIFICATION', 'BOOLEAN', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'OBJECTIVE_1', 'OBJECTIVE 1', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'OBJECTIVE_2', 'OBJECTIVE 2', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'OBJECTIVE_3', 'OBJECTIVE 3', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'PRIORITY_PROGRAM', 'PRIORITY PROGRAM', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'PRIORITY_PROGRAM_DESCRIPTION', 'PRIORITY PROGRAM DESCRIPTION', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'PTB_PROGRESS', 'PTB PROGRESS', 'NUMBER', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'RECOMMENDATION', 'RECOMMENDATION', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'TRAVEL_METHOD', 'TRAVEL METHOD', 'STRING', NULL);
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_TNSP_TRAIN_EVAL'), 'TRAINEE_UNIT_ID', 'TRAINEE_UNIT ID', 'STRING',  'UNIT_ID');
INSERT INTO ISWL_CUSTOM_REPORT_VIEW_FIELD (ID,VIEW_ID, COLUMN_NAME, DISPLAY_NAME, DATA_TYPE, REF_DATA_TYPE) VALUES
   (nextVal('SEQ_CUSTOM_REPORT_VIEW_FIELD'), (SELECT ID FROM ISWL_CUSTOM_REPORT_VIEW WHERE VIEW_NAME = 'ISWV_CR_RESOURCE_COST'), 'COST_LEVEL', 'COST LEVEL', 'STRING', NULL);
CREATE OR REPLACE VIEW ISWV_CR_RESOURCE_COST AS 
  SELECT DISTINCT
            i.id AS incident_id,
             i.incident_name AS incident_name,
             unit.unit_code || '-' || i.nbr AS incident_number,
             ac.account_code AS accounting_code,
             acc.code AS accrual_code,
             acc.description AS accrual_description,
             irdc.activity_date AS activity_date,
             agcy.agency_code AS agency_code,
             agcy.agency_name AS agency_description,
             irdc.aircraft_cost_amount AS aircraft_cost,
             cg.cost_group_name AS cost_group,
             cg.description AS cost_group_description,
             irdc.rate_type AS cost_UOM,
             CAST (
                CASE WHEN k.is_direct THEN 'Y' ELSE 'N' END AS text)
                AS is_direct,
             irdc.flight_hours AS flight_hrs,
             irdc.total_cost_amount AS grand_total_cost,
             gc.code AS group_code,
             k.code AS item_code,
             k.description AS item_description,
             irdc.cargo_pounds AS lbs_cargo,
             irdc.number_of_trips AS num_trips,
             r.parent_resource_id AS parent_id,
             irdc.number_of_passengers AS passenger,
             pagcy.agency_code AS payment_agency_code,
             pagcy.agency_name AS payment_agency_description,
             irdc.primary_total_amount AS primary_cost,
             a.request_number AS request_number,
             CAST (
                    CASE
                        WHEN r.is_person THEN
                            r.last_name
                            || CASE
                                    WHEN r.first_name IS NULL THEN ''
                                    ELSE ', ' || r.first_name
                                END
                        ELSE
                            r.resource_name
                    END AS character varying)
                    AS Resource_Name,
             irdc.retardant_gallons AS retardant_gal,
             dpt.code AS section_code,
             dpt.description AS section_description,
             shft.shift_name AS shift,
             sgc.code AS sub_group_code,
             irdc.subordinate_total_amount AS subordinate_cost,
             irdc.unit_cost_amount AS unit_cost,
             o.organization_name AS unit_description,
             o.unit_code AS unit_id,
             irdc.units AS units,
             irdc.water_gallons AS water_gal,
             irdc.cost_level AS cost_level
      FROM isw_incident i
             LEFT JOIN isw_organization unit
                 ON i.unit_id = unit.id
             LEFT OUTER JOIN isw_incident_resource ir
                 ON i.id = ir.incident_id
             LEFT OUTER JOIN isw_inc_res_daily_cost irdc
                 ON ir.id = irdc.incident_resource_id
             LEFT OUTER JOIN isw_cost_group cg
                 ON irdc.cost_group_id = cg.id
             LEFT OUTER JOIN isw_incident_account_code iac
                ON irdc.incident_account_code_id = iac.id
             LEFT OUTER JOIN isw_account_code ac
                 ON iac.account_code_id = ac.id
             LEFT OUTER JOIN iswl_accrual_code acc
                 ON irdc.accrual_code_id = acc.id
             LEFT OUTER JOIN isw_resource r
                 ON ir.resource_id = r.id
             LEFT OUTER JOIN iswl_agency agcy
                 ON r.agency_id = agcy.id
             LEFT OUTER JOIN isw_work_period wp
                 ON ir.id = wp.incident_resource_id
             LEFT OUTER JOIN isw_work_period_assignment wpa
                 ON wp.id = wpa.work_period_id
             LEFT OUTER JOIN isw_assignment a
                 ON wpa.assignment_id = a.id    
             LEFT OUTER JOIN iswl_kind k
                 ON a.kind_id = k.id
             LEFT OUTER JOIN iswl_group_category gc
                 ON k.group_category_id = gc.id
             LEFT OUTER JOIN isw_cost_data cd
                 ON ir.cost_data_id = cd.id
             LEFT OUTER JOIN iswl_agency pagcy
                 ON cd.payment_agency_id = pagcy.id
             LEFT OUTER JOIN iswl_department dpt
                 ON k.department_id = dpt.id
             LEFT OUTER JOIN isw_incident_shift shft
                 ON irdc.incident_shift_id = shft.id
             LEFT OUTER JOIN iswl_sub_group_category sgc
                 ON k.sub_group_category_id = sgc.id
             LEFT OUTER JOIN isw_organization o
                 ON r.organization_id = o.id;

 CREATE OR REPLACE VIEW iswv_cr_tnsp_train_eval AS 
 SELECT DISTINCT r.id AS resource_id, 
    get_resource_level(r.id) AS resource_level, 
        CASE
            WHEN r.is_person THEN (r.last_name::text || 
            CASE
                WHEN r.first_name IS NULL THEN ''::text
                ELSE ', '::text || r.first_name::text
            END)::character varying
            ELSE r.resource_name
        END AS trainee_resource_name, 
    r.last_name AS trainee_last_name, r.first_name AS trainee_first_name, 
    r.phone AS cellphone, r.other_1 AS other1, r.other_2 AS other2, 
    r.other_3 AS other3, r.parent_resource_id AS parent_id, 
    ag.agency_code AS agency, rm.start_date AS mobilization_date, 
    org.unit_code AS trainee_unit_id, i.id AS incident_id, i.incident_name, 
    (unit.unit_code::text || '-'::text) || i.nbr::text AS incident_number, 
        CASE
            WHEN k.is_line_overhead THEN 'Y'::text
            ELSE 'N'::text
        END AS line_overhead, 
    k.code AS item_code, k.description AS item_code_description, 
    dpt.code AS section_code, dpt.description AS section_description, 
    wp.dm_release_date AS actual_release_date, 
    wp.dm_release_date AS actual_release_time, 
    wp.ci_check_in_date AS check_in_date, wp.ci_check_in_date AS check_in_time, 
        CASE
            WHEN NOT wp.ci_first_work_date IS NULL AND NOT wp.ci_length_at_assignment IS NULL THEN wp.ci_first_work_date + '1 day'::interval * wp.ci_length_at_assignment::double precision
            ELSE NULL::timestamp without time zone
        END AS demobilization_date, 
    wp.dm_tentative_demob_city AS demobilization_city, 
    ics.cs_abbreviation AS demobilization_state, 
    wp.dm_tentative_release_date AS tentative_release_date, 
    wp.dm_tentative_release_date AS tentative_release_time, at.employment_type, 
    wp.ci_first_work_date AS first_day_of_work, 
    wp.ci_length_at_assignment AS length_of_assignment, 
    wp.ci_pre_planning_remarks AS remarks_plans, 
    wp.ci_travel_method AS travel_method, 
    wp.dm_travel_method AS return_method_of_travel, 
    a.request_number AS trainee_request_number, 
        CASE
            WHEN a.is_training THEN 'Y'::text
            ELSE 'N'::text
        END AS trainee, 
    comp.code AS assignment_complexity, rtk.code AS assignment_item_code, 
    rtk.description AS assignment_item_code_desc, 
    rt.number_of_acres AS assignment_acres, 
    rt.start_date AS assignment_start_date, rt.end_date AS assignment_end_date, 
    date_part('day'::text, rt.end_date - rt.start_date) AS length_of_trainee_assignment, 
    rt.ptb_percentage AS ptb_progress, recommend.code AS recommendation, 
    recommend.description AS recommendation_desc, 
    ( SELECT rtobj.objective
           FROM isw_rsc_training_objective rtobj
          WHERE rtobj.resource_training_id = rtt.resource_training_id AND rtobj.position_num = 1) AS objective_1, 
    ( SELECT rtobj.objective
           FROM isw_rsc_training_objective rtobj
          WHERE rtobj.resource_training_id = rtt.resource_training_id AND rtobj.position_num = 2) AS objective_2, 
    ( SELECT rtobj.objective
           FROM isw_rsc_training_objective rtobj
          WHERE rtobj.resource_training_id = rtt.resource_training_id AND rtobj.position_num = 3) AS objective_3, 
    pp.code AS priority_program_description, 
    rt.is_fs_priority_trainee AS priority_program, 
    a.assignment_status AS status, 
    rt.is_initial_assignment AS initial_assignment, 
    rt.is_valid_red_card AS redcard_assignment_cert, 
        CASE
            WHEN rt.incident_task_book::text = 'Y'::text THEN 'Y'::text
            ELSE 'N'::text
        END AS incident_issued_taskbook, 
        CASE
            WHEN rt.incident_task_book::text = 'N'::text THEN 'Y'::text
            ELSE 'N'::text
        END AS current_home_unit_taskbook, 
    huc.contact_name AS home_unit_contact_name, 
    huc.email AS home_unit_contact_email, huc.phone AS home_unit_contact_phone, 
        CASE
            WHEN hucaddr.address_line_1 IS NULL THEN ''::character varying
            ELSE hucaddr.address_line_1
        END::text || 
        CASE
            WHEN hucaddr.address_line_2 IS NULL THEN ''::text
            WHEN hucaddr.address_line_2='' THEN ''::text
            ELSE ', '::text || hucaddr.address_line_2::text
        END AS home_unit_contact_address, 
    hucaddr.city AS home_unit_contact_city, 
        CASE
            WHEN hatcounty.cs_abbreviation IS NULL THEN ''::character varying
            ELSE hatcounty.cs_abbreviation
        END AS home_unit_contact_state, 
    hucaddr.postal_code AS home_unit_contact_zip, 
    hucorg.unit_code AS home_unit_contact_unit_id, 
    hucorg.organization_name AS home_unit_contact_unit_id_desc, 
    ( SELECT ft.code
           FROM iswl_fuel_type ft
          WHERE ft.code::text = 'B'::text AND rtft.resource_training_id = rt.id) AS assignment_fuel_type_b, 
    ( SELECT ft.code
           FROM iswl_fuel_type ft
          WHERE ft.code::text = 'G'::text AND rtft.resource_training_id = rt.id) AS assignment_fuel_type_g, 
    ( SELECT ft.code
           FROM iswl_fuel_type ft
          WHERE ft.code::text = 'S'::text AND rtft.resource_training_id = rt.id) AS assignment_fuel_type_s, 
    ( SELECT ft.code
           FROM iswl_fuel_type ft
          WHERE ft.code::text = 'T'::text AND rtft.resource_training_id = rt.id) AS assignment_fuel_type_t, 
    rtt.reqest_number AS evaluator_request_number, 
        CASE
            WHEN rtt.incident_resource_id IS NULL THEN ''::text
            ELSE rtt.resource_name::text
        END AS evaluator_incident, 
    tek.code AS evaluator_item_code, 
    tek.description AS evaluator_item_code_desc, 
        CASE
            WHEN addr.address_line_1 IS NULL THEN ''::character varying
            ELSE addr.address_line_1
        END::text || 
        CASE
            WHEN addr.address_line_2 IS NULL THEN ''::text
            WHEN addr.address_line_2='' THEN ''::text
            ELSE ', '::text || addr.address_line_2::text
        END AS evaluator_address, 
    addr.city AS evaluator_city, 
        CASE
            WHEN atcounty.cs_abbreviation IS NULL THEN ''::character varying
            ELSE atcounty.cs_abbreviation
        END AS evaluator_state, 
    addr.postal_code AS evaluator_zip, rtt.email AS evaluator_email, 
    rtt.phone AS evaluator_phone, evaluatororg.unit_code AS evaluator_unit_id, 
    evaluatororg.organization_name AS evaluator_unit_id_desc, 
        CASE
            WHEN rtt.incident_resource_id IS NULL THEN rtt.resource_name::text
            ELSE ''::text
        END AS evaluator_non_incident, 
    rtta.assignment_status AS evaluator_status
   FROM isw_resource_training rt
   JOIN isw_incident_resource ir ON rt.incident_resource_id = ir.id
   JOIN isw_resource r ON ir.resource_id = r.id
   JOIN isw_incident i ON ir.incident_id = i.id
   LEFT JOIN iswl_agency ag ON r.agency_id = ag.id
   LEFT JOIN isw_resource_mobilization rm ON r.id = rm.resource_id
   LEFT JOIN isw_organization org ON r.organization_id = org.id
   LEFT JOIN isw_organization unit ON i.unit_id = unit.id
   LEFT JOIN isw_work_period wp ON ir.id = wp.incident_resource_id
   LEFT JOIN iswl_country_subdivision ics ON wp.dm_tentative_demob_state_id = ics.id
   LEFT JOIN isw_work_period_assignment wpa ON wp.id = wpa.work_period_id
   LEFT JOIN isw_assignment a ON wpa.assignment_id = a.id
   LEFT JOIN isw_assignment_time at ON a.id = at.assignment_id
   LEFT JOIN iswl_kind k ON a.kind_id = k.id
   LEFT JOIN iswl_department dpt ON k.department_id = dpt.id
   LEFT JOIN isw_rsc_training_trainer rtt ON rtt.resource_training_id = rt.id
   LEFT JOIN iswl_complexity comp ON comp.id = rt.complexity_id
   LEFT JOIN isw_incident_resource teir ON teir.id = rtt.incident_resource_id
   LEFT JOIN isw_organization evaluatororg ON rtt.unit_id = evaluatororg.id
   LEFT JOIN isw_address addr ON rtt.address_id = addr.id
   LEFT JOIN iswl_country_subdivision atcounty ON addr.country_subdivision_id = atcounty.id
   LEFT JOIN iswl_kind tek ON tek.id = rtt.kind_id
   JOIN iswl_kind rtk ON rtk.id = rt.kind_id
   LEFT JOIN iswl_priority_program pp ON pp.id = rt.priority_program_id
   LEFT JOIN iswl_recommendation recommend ON rt.recommendation_id = recommend.id
   LEFT JOIN isw_rsc_training_fuel_type rtft ON rtt.resource_training_id = rtft.resource_training_id
   LEFT JOIN isw_rsc_training_objective rtobj ON rtt.resource_training_id = rtobj.resource_training_id
   LEFT JOIN isw_resource_home_unit_contact huc ON rt.incident_resource_id = huc.incident_resource_id
   LEFT JOIN isw_address hucaddr ON huc.address_id = hucaddr.id
   LEFT JOIN iswl_country_subdivision hatcounty ON hucaddr.country_subdivision_id = hatcounty.id
   LEFT JOIN isw_organization hucorg ON huc.unit_id = hucorg.id
   LEFT JOIN isw_work_period rttwp ON rtt.incident_resource_id = rttwp.incident_resource_id
   LEFT JOIN isw_work_period_assignment rttwpa ON rttwp.id = rttwpa.work_period_id
   LEFT JOIN isw_assignment rtta ON rttwpa.assignment_id = rtta.id
  WHERE r.deleted_date IS NULL;

INSERT INTO ISW_ORGANIZATION (ID, UNIT_CODE, ORGANIZATION_NAME, AGENCY_ID, IS_DISPATCH_CENTER, IS_LOCAL, IS_STANDARD, IS_ACTIVE,  TRANSFERABLE_IDENTITY)  VALUES (nextVal('SEQ_ORGANIZATION'), 'OR-RVC', 'ROGUE VALLEY INTERAGENCY COMMUNICATION CENTER', (select id from iswl_agency where agency_code = 'IAC'), TRUE, FALSE, TRUE, 'Y', 'EEDE7726852039C9960F3531BF3857EC');
INSERT INTO SCHEMACHANGELOG( ID, MAJORRELEASENUMBER, MINORRELEASENUMBER, POINTRELEASENUMBER, SCRIPTNAME, DATEAPPLIED)
VALUES (243,'01','02','01.00','patch.243.sc-pg.01_02_01.00.sql', now());
UPDATE REVISION SET REVISIONLEVEL = 243;