//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 09:27:25 AM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ibm.com/xmlns/prod/cognos/dataSet/201006", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.nwcg.isuite.xml.ross2;
