//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 09:27:25 AM MDT 
//


package gov.nwcg.isuite.xml.ross2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IncNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IncName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IncState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InitialDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IncDispOrgUnitCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MergedIncFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreviousIncNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IncType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IncAgencyAbbrev" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReqID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReqStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RootReqFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReqNumberPrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReqNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AssignmentName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReqStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReqCatalogName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReqCategoryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FilledCatalogItemCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FilledCatalogItemName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MobETD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResProvUnitCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VendorOwnedFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VendorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="JetPort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResProvAgencyAbbrev" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmploymentClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "incID",
    "incNumber",
    "incName",
    "incState",
    "initialDate",
    "incDispOrgUnitCode",
    "mergedIncFlag",
    "previousIncNumber",
    "incType",
    "incAgencyAbbrev",
    "reqID",
    "reqStatusCode",
    "rootReqFlag",
    "reqNumberPrefix",
    "reqNumber",
    "assignmentName",
    "reqStatus",
    "reqCatalogName",
    "reqCategoryName",
    "filledCatalogItemCode",
    "filledCatalogItemName",
    "contractType",
    "contractNumber",
    "mobETD",
    "resID",
    "resName",
    "lastName",
    "firstName",
    "middleName",
    "resProvUnitCode",
    "vendorOwnedFlag",
    "vendorName",
    "jetPort",
    "resProvAgencyAbbrev",
    "employmentClass"
})
@XmlRootElement(name = "row")
public class Row {

    @XmlElement(name = "IncID")
    protected String incID;
    @XmlElement(name = "IncNumber")
    protected String incNumber;
    @XmlElement(name = "IncName")
    protected String incName;
    @XmlElement(name = "IncState")
    protected String incState;
    @XmlElement(name = "InitialDate")
    protected String initialDate;
    @XmlElement(name = "IncDispOrgUnitCode")
    protected String incDispOrgUnitCode;
    @XmlElement(name = "MergedIncFlag")
    protected String mergedIncFlag;
    @XmlElement(name = "PreviousIncNumber")
    protected String previousIncNumber;
    @XmlElement(name = "IncType")
    protected String incType;
    @XmlElement(name = "IncAgencyAbbrev")
    protected String incAgencyAbbrev;
    @XmlElement(name = "ReqID")
    protected String reqID;
    @XmlElement(name = "ReqStatusCode")
    protected String reqStatusCode;
    @XmlElement(name = "RootReqFlag")
    protected String rootReqFlag;
    @XmlElement(name = "ReqNumberPrefix")
    protected String reqNumberPrefix;
    @XmlElement(name = "ReqNumber")
    protected String reqNumber;
    @XmlElement(name = "AssignmentName")
    protected String assignmentName;
    @XmlElement(name = "ReqStatus")
    protected String reqStatus;
    @XmlElement(name = "ReqCatalogName")
    protected String reqCatalogName;
    @XmlElement(name = "ReqCategoryName")
    protected String reqCategoryName;
    @XmlElement(name = "FilledCatalogItemCode")
    protected String filledCatalogItemCode;
    @XmlElement(name = "FilledCatalogItemName")
    protected String filledCatalogItemName;
    @XmlElement(name = "ContractType")
    protected String contractType;
    @XmlElement(name = "ContractNumber")
    protected String contractNumber;
    @XmlElement(name = "MobETD")
    protected String mobETD;
    @XmlElement(name = "ResID")
    protected String resID;
    @XmlElement(name = "ResName")
    protected String resName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "ResProvUnitCode")
    protected String resProvUnitCode;
    @XmlElement(name = "VendorOwnedFlag")
    protected String vendorOwnedFlag;
    @XmlElement(name = "VendorName")
    protected String vendorName;
    @XmlElement(name = "JetPort")
    protected String jetPort;
    @XmlElement(name = "ResProvAgencyAbbrev")
    protected String resProvAgencyAbbrev;
    @XmlElement(name = "EmploymentClass")
    protected String employmentClass;

    /**
     * Gets the value of the incID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncID() {
        return incID;
    }

    /**
     * Sets the value of the incID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncID(String value) {
        this.incID = value;
    }

    /**
     * Gets the value of the incNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncNumber() {
        return incNumber;
    }

    /**
     * Sets the value of the incNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncNumber(String value) {
        this.incNumber = value;
    }

    /**
     * Gets the value of the incName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncName() {
        return incName;
    }

    /**
     * Sets the value of the incName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncName(String value) {
        this.incName = value;
    }

    /**
     * Gets the value of the incState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncState() {
        return incState;
    }

    /**
     * Sets the value of the incState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncState(String value) {
        this.incState = value;
    }

    /**
     * Gets the value of the initialDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialDate() {
        return initialDate;
    }

    /**
     * Sets the value of the initialDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialDate(String value) {
        this.initialDate = value;
    }

    /**
     * Gets the value of the incDispOrgUnitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncDispOrgUnitCode() {
        return incDispOrgUnitCode;
    }

    /**
     * Sets the value of the incDispOrgUnitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncDispOrgUnitCode(String value) {
        this.incDispOrgUnitCode = value;
    }

    /**
     * Gets the value of the mergedIncFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMergedIncFlag() {
        return mergedIncFlag;
    }

    /**
     * Sets the value of the mergedIncFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMergedIncFlag(String value) {
        this.mergedIncFlag = value;
    }

    /**
     * Gets the value of the previousIncNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousIncNumber() {
        return previousIncNumber;
    }

    /**
     * Sets the value of the previousIncNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousIncNumber(String value) {
        this.previousIncNumber = value;
    }

    /**
     * Gets the value of the incType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncType() {
        return incType;
    }

    /**
     * Sets the value of the incType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncType(String value) {
        this.incType = value;
    }

    /**
     * Gets the value of the incAgencyAbbrev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncAgencyAbbrev() {
        return incAgencyAbbrev;
    }

    /**
     * Sets the value of the incAgencyAbbrev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncAgencyAbbrev(String value) {
        this.incAgencyAbbrev = value;
    }

    /**
     * Gets the value of the reqID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqID() {
        return reqID;
    }

    /**
     * Sets the value of the reqID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqID(String value) {
        this.reqID = value;
    }

    /**
     * Gets the value of the reqStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqStatusCode() {
        return reqStatusCode;
    }

    /**
     * Sets the value of the reqStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqStatusCode(String value) {
        this.reqStatusCode = value;
    }

    /**
     * Gets the value of the rootReqFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootReqFlag() {
        return rootReqFlag;
    }

    /**
     * Sets the value of the rootReqFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootReqFlag(String value) {
        this.rootReqFlag = value;
    }

    /**
     * Gets the value of the reqNumberPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqNumberPrefix() {
        return reqNumberPrefix;
    }

    /**
     * Sets the value of the reqNumberPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqNumberPrefix(String value) {
        this.reqNumberPrefix = value;
    }

    /**
     * Gets the value of the reqNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqNumber() {
        return reqNumber;
    }

    /**
     * Sets the value of the reqNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqNumber(String value) {
        this.reqNumber = value;
    }

    /**
     * Gets the value of the assignmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignmentName() {
        return assignmentName;
    }

    /**
     * Sets the value of the assignmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignmentName(String value) {
        this.assignmentName = value;
    }

    /**
     * Gets the value of the reqStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqStatus() {
        return reqStatus;
    }

    /**
     * Sets the value of the reqStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqStatus(String value) {
        this.reqStatus = value;
    }

    /**
     * Gets the value of the reqCatalogName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqCatalogName() {
        return reqCatalogName;
    }

    /**
     * Sets the value of the reqCatalogName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqCatalogName(String value) {
        this.reqCatalogName = value;
    }

    /**
     * Gets the value of the reqCategoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqCategoryName() {
        return reqCategoryName;
    }

    /**
     * Sets the value of the reqCategoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqCategoryName(String value) {
        this.reqCategoryName = value;
    }

    /**
     * Gets the value of the filledCatalogItemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilledCatalogItemCode() {
        return filledCatalogItemCode;
    }

    /**
     * Sets the value of the filledCatalogItemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilledCatalogItemCode(String value) {
        this.filledCatalogItemCode = value;
    }

    /**
     * Gets the value of the filledCatalogItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilledCatalogItemName() {
        return filledCatalogItemName;
    }

    /**
     * Sets the value of the filledCatalogItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilledCatalogItemName(String value) {
        this.filledCatalogItemName = value;
    }

    /**
     * Gets the value of the contractType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * Sets the value of the contractType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractType(String value) {
        this.contractType = value;
    }

    /**
     * Gets the value of the contractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * Sets the value of the contractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNumber(String value) {
        this.contractNumber = value;
    }

    /**
     * Gets the value of the mobETD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobETD() {
        return mobETD;
    }

    /**
     * Sets the value of the mobETD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobETD(String value) {
        this.mobETD = value;
    }

    /**
     * Gets the value of the resID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResID() {
        return resID;
    }

    /**
     * Sets the value of the resID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResID(String value) {
        this.resID = value;
    }

    /**
     * Gets the value of the resName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResName() {
        return resName;
    }

    /**
     * Sets the value of the resName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResName(String value) {
        this.resName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the resProvUnitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResProvUnitCode() {
        return resProvUnitCode;
    }

    /**
     * Sets the value of the resProvUnitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResProvUnitCode(String value) {
        this.resProvUnitCode = value;
    }

    /**
     * Gets the value of the vendorOwnedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorOwnedFlag() {
        return vendorOwnedFlag;
    }

    /**
     * Sets the value of the vendorOwnedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorOwnedFlag(String value) {
        this.vendorOwnedFlag = value;
    }

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the jetPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJetPort() {
        return jetPort;
    }

    /**
     * Sets the value of the jetPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJetPort(String value) {
        this.jetPort = value;
    }

    /**
     * Gets the value of the resProvAgencyAbbrev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResProvAgencyAbbrev() {
        return resProvAgencyAbbrev;
    }

    /**
     * Sets the value of the resProvAgencyAbbrev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResProvAgencyAbbrev(String value) {
        this.resProvAgencyAbbrev = value;
    }

    /**
     * Gets the value of the employmentClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentClass() {
        return employmentClass;
    }

    /**
     * Sets the value of the employmentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentClass(String value) {
        this.employmentClass = value;
    }

}
