//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 03:42:17 PM MDT 
//


package gov.nwcg.isuite.xml.customreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ColumnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ColumnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ColumnName" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50"/>
 *         &lt;element name="DisplayOrder">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="70"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Header" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50"/>
 *         &lt;element name="Width">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="600"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AggregateType" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="FormatType" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="SortBySeq" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SortByType" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength20" minOccurs="0"/>
 *         &lt;element name="GroupBySeq" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="GroupByType" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength20" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColumnType", propOrder = {
    "columnName",
    "displayOrder",
    "header",
    "width",
    "aggregateType",
    "formatType",
    "sortBySeq",
    "sortByType",
    "groupBySeq",
    "groupByType"
})
public class ColumnType {

    @XmlElement(name = "ColumnName", required = true)
    protected String columnName;
    @XmlElement(name = "DisplayOrder")
    protected int displayOrder;
    @XmlElement(name = "Header", required = true)
    protected String header;
    @XmlElement(name = "Width")
    protected int width;
    @XmlElement(name = "AggregateType")
    protected String aggregateType;
    @XmlElement(name = "FormatType")
    protected String formatType;
    @XmlElement(name = "SortBySeq")
    protected Integer sortBySeq;
    @XmlElement(name = "SortByType")
    protected String sortByType;
    @XmlElement(name = "GroupBySeq")
    protected Integer groupBySeq;
    @XmlElement(name = "GroupByType")
    protected String groupByType;

    /**
     * Gets the value of the columnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * Sets the value of the columnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnName(String value) {
        this.columnName = value;
    }

    /**
     * Gets the value of the displayOrder property.
     * 
     */
    public int getDisplayOrder() {
        return displayOrder;
    }

    /**
     * Sets the value of the displayOrder property.
     * 
     */
    public void setDisplayOrder(int value) {
        this.displayOrder = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeader(String value) {
        this.header = value;
    }

    /**
     * Gets the value of the width property.
     * 
     */
    public int getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     */
    public void setWidth(int value) {
        this.width = value;
    }

    /**
     * Gets the value of the aggregateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAggregateType() {
        return aggregateType;
    }

    /**
     * Sets the value of the aggregateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAggregateType(String value) {
        this.aggregateType = value;
    }

    /**
     * Gets the value of the formatType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatType() {
        return formatType;
    }

    /**
     * Sets the value of the formatType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatType(String value) {
        this.formatType = value;
    }

    /**
     * Gets the value of the sortBySeq property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSortBySeq() {
        return sortBySeq;
    }

    /**
     * Sets the value of the sortBySeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSortBySeq(Integer value) {
        this.sortBySeq = value;
    }

    /**
     * Gets the value of the sortByType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortByType() {
        return sortByType;
    }

    /**
     * Sets the value of the sortByType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortByType(String value) {
        this.sortByType = value;
    }

    /**
     * Gets the value of the groupBySeq property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGroupBySeq() {
        return groupBySeq;
    }

    /**
     * Sets the value of the groupBySeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGroupBySeq(Integer value) {
        this.groupBySeq = value;
    }

    /**
     * Gets the value of the groupByType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupByType() {
        return groupByType;
    }

    /**
     * Sets the value of the groupByType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupByType(String value) {
        this.groupByType = value;
    }

}
