//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 04:52:06 PM EDT 
//


package gov.nwcg.isuite.xml.customreport;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CRColumnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CRColumnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FieldName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DisplayOrder" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="FormatType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RefTable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SortBySeq" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="SortByType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GroupBySeq" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="GroupByType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CRColumnType", propOrder = {
    "fieldName",
    "caption",
    "displayOrder",
    "width",
    "formatType",
    "refTable",
    "sortBySeq",
    "sortByType",
    "groupBySeq",
    "groupByType"
})
public class CRColumnType {

    @XmlElement(name = "FieldName", required = true)
    protected String fieldName;
    @XmlElement(name = "Caption", required = true)
    protected String caption;
    @XmlElement(name = "DisplayOrder", required = true)
    protected BigInteger displayOrder;
    @XmlElement(name = "Width")
    protected long width;
    @XmlElement(name = "FormatType", required = true)
    protected String formatType;
    @XmlElement(name = "RefTable", required = true)
    protected String refTable;
    @XmlElement(name = "SortBySeq", required = true)
    protected BigInteger sortBySeq;
    @XmlElement(name = "SortByType", required = true)
    protected String sortByType;
    @XmlElement(name = "GroupBySeq", required = true)
    protected BigInteger groupBySeq;
    @XmlElement(name = "GroupByType", required = true)
    protected String groupByType;

    /**
     * Gets the value of the fieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Sets the value of the fieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldName(String value) {
        this.fieldName = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the displayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisplayOrder() {
        return displayOrder;
    }

    /**
     * Sets the value of the displayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisplayOrder(BigInteger value) {
        this.displayOrder = value;
    }

    /**
     * Gets the value of the width property.
     * 
     */
    public long getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     */
    public void setWidth(long value) {
        this.width = value;
    }

    /**
     * Gets the value of the formatType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatType() {
        return formatType;
    }

    /**
     * Sets the value of the formatType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatType(String value) {
        this.formatType = value;
    }

    /**
     * Gets the value of the refTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefTable() {
        return refTable;
    }

    /**
     * Sets the value of the refTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefTable(String value) {
        this.refTable = value;
    }

    /**
     * Gets the value of the sortBySeq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSortBySeq() {
        return sortBySeq;
    }

    /**
     * Sets the value of the sortBySeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSortBySeq(BigInteger value) {
        this.sortBySeq = value;
    }

    /**
     * Gets the value of the sortByType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortByType() {
        return sortByType;
    }

    /**
     * Sets the value of the sortByType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortByType(String value) {
        this.sortByType = value;
    }

    /**
     * Gets the value of the groupBySeq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGroupBySeq() {
        return groupBySeq;
    }

    /**
     * Sets the value of the groupBySeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGroupBySeq(BigInteger value) {
        this.groupBySeq = value;
    }

    /**
     * Gets the value of the groupByType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupByType() {
        return groupByType;
    }

    /**
     * Sets the value of the groupByType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupByType(String value) {
        this.groupByType = value;
    }

}
