//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 03:42:17 PM MDT 
//


package gov.nwcg.isuite.xml.customreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CriteriaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CriteriaType" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength1"/>
 *         &lt;element name="Connective" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="SourceViewFieldSQLName" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="SourceInputValue" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="SourceEvaluatorType" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="OperatorType" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="TargetType" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="TargetValue1" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="TargetValue2" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="TargetViewFieldSQLName" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="TargetList" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength200" minOccurs="0"/>
 *         &lt;element name="TargetTermType" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="TargetEvaluatorType" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="ChildrenCriterias" type="{http://isuite.nwcg.gov/CustomReportExport}CriteriaListType" minOccurs="0"/>
 *         &lt;element name="DisplayOrder" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="GroupID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="ParentGroupID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CriteriaType", propOrder = {
    "criteriaType",
    "connective",
    "sourceViewFieldSQLName",
    "sourceInputValue",
    "sourceEvaluatorType",
    "operatorType",
    "targetType",
    "targetValue1",
    "targetValue2",
    "targetViewFieldSQLName",
    "targetList",
    "targetTermType",
    "targetEvaluatorType",
    "childrenCriterias",
    "displayOrder",
    "groupID",
    "parentGroupID"
})
public class CriteriaType {

    @XmlElement(name = "CriteriaType", required = true)
    protected String criteriaType;
    @XmlElement(name = "Connective")
    protected String connective;
    @XmlElement(name = "SourceViewFieldSQLName")
    protected String sourceViewFieldSQLName;
    @XmlElement(name = "SourceInputValue")
    protected String sourceInputValue;
    @XmlElement(name = "SourceEvaluatorType")
    protected String sourceEvaluatorType;
    @XmlElement(name = "OperatorType")
    protected String operatorType;
    @XmlElement(name = "TargetType")
    protected String targetType;
    @XmlElement(name = "TargetValue1")
    protected String targetValue1;
    @XmlElement(name = "TargetValue2")
    protected String targetValue2;
    @XmlElement(name = "TargetViewFieldSQLName")
    protected String targetViewFieldSQLName;
    @XmlElement(name = "TargetList")
    protected String targetList;
    @XmlElement(name = "TargetTermType")
    protected String targetTermType;
    @XmlElement(name = "TargetEvaluatorType")
    protected String targetEvaluatorType;
    @XmlElement(name = "ChildrenCriterias")
    protected CriteriaListType childrenCriterias;
    @XmlElement(name = "DisplayOrder")
    protected Integer displayOrder;
    @XmlElement(name = "GroupID")
    protected Long groupID;
    @XmlElement(name = "ParentGroupID")
    protected Long parentGroupID;

    /**
     * Gets the value of the criteriaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCriteriaType() {
        return criteriaType;
    }

    /**
     * Sets the value of the criteriaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCriteriaType(String value) {
        this.criteriaType = value;
    }

    /**
     * Gets the value of the connective property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnective() {
        return connective;
    }

    /**
     * Sets the value of the connective property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnective(String value) {
        this.connective = value;
    }

    /**
     * Gets the value of the sourceViewFieldSQLName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceViewFieldSQLName() {
        return sourceViewFieldSQLName;
    }

    /**
     * Sets the value of the sourceViewFieldSQLName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceViewFieldSQLName(String value) {
        this.sourceViewFieldSQLName = value;
    }

    /**
     * Gets the value of the sourceInputValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceInputValue() {
        return sourceInputValue;
    }

    /**
     * Sets the value of the sourceInputValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceInputValue(String value) {
        this.sourceInputValue = value;
    }

    /**
     * Gets the value of the sourceEvaluatorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceEvaluatorType() {
        return sourceEvaluatorType;
    }

    /**
     * Sets the value of the sourceEvaluatorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceEvaluatorType(String value) {
        this.sourceEvaluatorType = value;
    }

    /**
     * Gets the value of the operatorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorType() {
        return operatorType;
    }

    /**
     * Sets the value of the operatorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorType(String value) {
        this.operatorType = value;
    }

    /**
     * Gets the value of the targetType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * Sets the value of the targetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetType(String value) {
        this.targetType = value;
    }

    /**
     * Gets the value of the targetValue1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetValue1() {
        return targetValue1;
    }

    /**
     * Sets the value of the targetValue1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetValue1(String value) {
        this.targetValue1 = value;
    }

    /**
     * Gets the value of the targetValue2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetValue2() {
        return targetValue2;
    }

    /**
     * Sets the value of the targetValue2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetValue2(String value) {
        this.targetValue2 = value;
    }

    /**
     * Gets the value of the targetViewFieldSQLName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetViewFieldSQLName() {
        return targetViewFieldSQLName;
    }

    /**
     * Sets the value of the targetViewFieldSQLName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetViewFieldSQLName(String value) {
        this.targetViewFieldSQLName = value;
    }

    /**
     * Gets the value of the targetList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetList() {
        return targetList;
    }

    /**
     * Sets the value of the targetList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetList(String value) {
        this.targetList = value;
    }

    /**
     * Gets the value of the targetTermType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetTermType() {
        return targetTermType;
    }

    /**
     * Sets the value of the targetTermType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetTermType(String value) {
        this.targetTermType = value;
    }

    /**
     * Gets the value of the targetEvaluatorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEvaluatorType() {
        return targetEvaluatorType;
    }

    /**
     * Sets the value of the targetEvaluatorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEvaluatorType(String value) {
        this.targetEvaluatorType = value;
    }

    /**
     * Gets the value of the childrenCriterias property.
     * 
     * @return
     *     possible object is
     *     {@link CriteriaListType }
     *     
     */
    public CriteriaListType getChildrenCriterias() {
        return childrenCriterias;
    }

    /**
     * Sets the value of the childrenCriterias property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriteriaListType }
     *     
     */
    public void setChildrenCriterias(CriteriaListType value) {
        this.childrenCriterias = value;
    }

    /**
     * Gets the value of the displayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * Sets the value of the displayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDisplayOrder(Integer value) {
        this.displayOrder = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setGroupID(Long value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the parentGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getParentGroupID() {
        return parentGroupID;
    }

    /**
     * Sets the value of the parentGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setParentGroupID(Long value) {
        this.parentGroupID = value;
    }

}
