//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 03:42:17 PM MDT 
//


package gov.nwcg.isuite.xml.customreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Title" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50"/>
 *         &lt;element name="Subtitle" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength200" minOccurs="0"/>
 *         &lt;element name="DataView" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50"/>
 *         &lt;element name="CreateDateTime" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ExportDateTime" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CreatorFirstName" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50"/>
 *         &lt;element name="CreatorLastName" type="{http://isuite.nwcg.gov/CustomReportExport}StringMaxLength50"/>
 *         &lt;element name="VisibleToPublic" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Landscape" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="LineSpacing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Criterias" type="{http://isuite.nwcg.gov/CustomReportExport}CriteriaListType" minOccurs="0"/>
 *         &lt;element name="Columns" type="{http://isuite.nwcg.gov/CustomReportExport}ColumnListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "subtitle",
    "description",
    "dataView",
    "createDateTime",
    "exportDateTime",
    "creatorFirstName",
    "creatorLastName",
    "visibleToPublic",
    "landscape",
    "lineSpacing",
    "criterias",
    "columns"
})
@XmlRootElement(name = "CustomReportExport")
public class CustomReportExport {

    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "Subtitle")
    protected String subtitle;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "DataView", required = true)
    protected String dataView;
    @XmlElement(name = "CreateDateTime")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar createDateTime;
    @XmlElement(name = "ExportDateTime")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar exportDateTime;
    @XmlElement(name = "CreatorFirstName", required = true)
    protected String creatorFirstName;
    @XmlElement(name = "CreatorLastName", required = true)
    protected String creatorLastName;
    @XmlElement(name = "VisibleToPublic")
    protected boolean visibleToPublic;
    @XmlElement(name = "Landscape")
    protected boolean landscape;
    @XmlElement(name = "LineSpacing", required = true)
    protected String lineSpacing;
    @XmlElement(name = "Criterias")
    protected CriteriaListType criterias;
    @XmlElement(name = "Columns", required = true)
    protected ColumnListType columns;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the subtitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * Sets the value of the subtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtitle(String value) {
        this.subtitle = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the dataView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataView() {
        return dataView;
    }

    /**
     * Sets the value of the dataView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataView(String value) {
        this.dataView = value;
    }

    /**
     * Gets the value of the createDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDateTime() {
        return createDateTime;
    }

    /**
     * Sets the value of the createDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDateTime(XMLGregorianCalendar value) {
        this.createDateTime = value;
    }

    /**
     * Gets the value of the exportDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExportDateTime() {
        return exportDateTime;
    }

    /**
     * Sets the value of the exportDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExportDateTime(XMLGregorianCalendar value) {
        this.exportDateTime = value;
    }

    /**
     * Gets the value of the creatorFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatorFirstName() {
        return creatorFirstName;
    }

    /**
     * Sets the value of the creatorFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatorFirstName(String value) {
        this.creatorFirstName = value;
    }

    /**
     * Gets the value of the creatorLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatorLastName() {
        return creatorLastName;
    }

    /**
     * Sets the value of the creatorLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatorLastName(String value) {
        this.creatorLastName = value;
    }

    /**
     * Gets the value of the visibleToPublic property.
     * 
     */
    public boolean isVisibleToPublic() {
        return visibleToPublic;
    }

    /**
     * Sets the value of the visibleToPublic property.
     * 
     */
    public void setVisibleToPublic(boolean value) {
        this.visibleToPublic = value;
    }

    /**
     * Gets the value of the landscape property.
     * 
     */
    public boolean isLandscape() {
        return landscape;
    }

    /**
     * Sets the value of the landscape property.
     * 
     */
    public void setLandscape(boolean value) {
        this.landscape = value;
    }

    /**
     * Gets the value of the lineSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineSpacing() {
        return lineSpacing;
    }

    /**
     * Sets the value of the lineSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineSpacing(String value) {
        this.lineSpacing = value;
    }

    /**
     * Gets the value of the criterias property.
     * 
     * @return
     *     possible object is
     *     {@link CriteriaListType }
     *     
     */
    public CriteriaListType getCriterias() {
        return criterias;
    }

    /**
     * Sets the value of the criterias property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriteriaListType }
     *     
     */
    public void setCriterias(CriteriaListType value) {
        this.criterias = value;
    }

    /**
     * Gets the value of the columns property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnListType }
     *     
     */
    public ColumnListType getColumns() {
        return columns;
    }

    /**
     * Sets the value of the columns property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnListType }
     *     
     */
    public void setColumns(ColumnListType value) {
        this.columns = value;
    }

}
