//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.07 at 03:42:17 PM MDT 
//


package gov.nwcg.isuite.xml.customreport;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nwcg.isuite.xml.customreport package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nwcg.isuite.xml.customreport
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomReportExport }
     * 
     */
    public CustomReportExport createCustomReportExport() {
        return new CustomReportExport();
    }

    /**
     * Create an instance of {@link CriteriaListType }
     * 
     */
    public CriteriaListType createCriteriaListType() {
        return new CriteriaListType();
    }

    /**
     * Create an instance of {@link ColumnListType }
     * 
     */
    public ColumnListType createColumnListType() {
        return new ColumnListType();
    }

    /**
     * Create an instance of {@link ColumnType }
     * 
     */
    public ColumnType createColumnType() {
        return new ColumnType();
    }

    /**
     * Create an instance of {@link CriteriaType }
     * 
     */
    public CriteriaType createCriteriaType() {
        return new CriteriaType();
    }

}
