package gov.nwcg.isuite.framework.core.xmltransferv2.importer;

import gov.nwcg.isuite.core.domain.xmlv2.*;

public enum TableImportOrderEnum {
    IswlDepartment(IswlDepartment.class)
	,IswlDepartmentSub(IswlDepartmentSub.class)
	,IswlRequestCategory(IswlRequestCategory.class)
	,IswlEventType(IswlEventType.class)
	,IswlDailyForm(IswlDailyForm.class)
	,IswlCountry(IswlCountry.class)
	,IswlSpecialPay(IswlSpecialPay.class)
	,IswlSubGroupCategory(IswlSubGroupCategory.class)
	,IswlGroupCategory(IswlGroupCategory.class)
	,IswlGraphGroup(IswlGraphGroup.class)
	,IswlRateGroup(IswlRateGroup.class)
	,IswlRateClass(IswlRateClass.class)
	,IswlRateClassRate(IswlRateClassRate.class)
	,IswAddress(IswAddress.class)
	,IswAdminOffice(IswAdminOffice.class)
	,IswIncident(IswIncident.class)
	,IswIncidentGroup(IswIncidentGroup.class)
	,IswIncidentGroupIncident(IswIncidentGroupIncident.class)
	,IswlKind(IswlKind.class)
	,IswlJetPort(IswlJetPort.class)
	,IswlAgency(IswlAgency.class)
	,IswOrganization(IswOrganization.class)
	,IswIncidentShift(IswIncidentShift.class)
	,IswIncidentCostDefaults(IswIncidentCostDefaults.class)
	,IswIncidentPrefsOtherFields(IswIncidentPrefsOtherFields.class)
	,IswIapMasterFrequency(IswIapMasterFrequency.class)
	,IswIapPositionItemCode(IswIapPositionItemCode.class)
	,IswAccountCode(IswAccountCode.class)
	,IswIncidentAccountCode(IswIncidentAccountCode.class)
	,IswIncidentQSKind(IswIncidentQSKind.class)
	,IswIncidentGroupQSKind(IswIncidentGroupQSKind.class)
	,IswIncidentPrefs(IswIncidentPrefs.class)
	,IswIncidentGroupPrefs(IswIncidentGroupPrefs.class)
	,IswQuestion(IswQuestion.class)
	,IswIncidentQuestion(IswIncidentQuestion.class)
	,IswIncidentGroupQuestion(IswIncidentGroupQuestion.class)
	,IswIncidentCostRate(IswIncidentCostRate.class)
	,IswIncidentCostRateState(IswIncidentCostRateState.class)
	,IswIncidentCostRateStateKind(IswIncidentCostRateStateKind.class)
	,IswIncidentCostRateKind(IswIncidentCostRateKind.class)
	,IswIncidentCostRateOvhd(IswIncidentCostRateOvhd.class)
	,IswCostGroup(IswCostGroup.class)
	,IswCostGroupAgencyDayShare(IswCostGroupAgencyDayShare.class)
	,IswCostGroupAgencyDaySharePercentage(IswCostGroupAgencyDaySharePercentage.class)
	,IswCostGroupDefaultAgencyDaySharePercentage(IswCostGroupDefaultAgencyDaySharePercentage.class)
	,IswContractor(IswContractor.class)
	,IswIncidentContractor(IswIncidentContractor.class)
	,IswContractorAgreement(IswContractorAgreement.class)
	,IswIapPlan(IswIapPlan.class)
	,IswIapAttachment(IswIapAttachment.class)
	,IswIapForm202(IswIapForm202.class)
	,IswIapForm203(IswIapForm203.class)
	,IswIapBranch(IswIapBranch.class)
	,IswIapBranchCommSummary(IswIapBranchCommSummary.class)
	,IswIapBranchPersonnel(IswIapBranchPersonnel.class)
	,IswIapBranchPersonnelRes(IswIapBranchPersonnelRes.class)
	,IswIapBranchRscAssign(IswIapBranchRscAssign.class)
	,IswIapForm205(IswIapForm205.class)
	,IswIapFrequency(IswIapFrequency.class)
	,IswIapForm206(IswIapForm206.class)
	,IswIapHospital(IswIapHospital.class)
	,IswIapMedicalAid(IswIapMedicalAid.class)
	,IswIapAreaLocationCapability(IswIapAreaLocationCapability.class)
	,IswIapRemoteCampLocation(IswIapRemoteCampLocation.class)
	,IswIapForm220(IswIapForm220.class)
	,IswIapAircraft(IswIapAircraft.class)
	,IswIapAircraftFrequency(IswIapAircraftFrequency.class)
	,IswIapAircraftTask(IswIapAircraftTask.class)
	,IswIapPersonnel(IswIapPersonnel.class)
	,IswIapPersonnelRes(IswIapPersonnelRes.class)
	,IswFinancialExport(IswFinancialExport.class)
	,IswResource(IswResource.class)
	,IswResourceKind(IswResourceKind.class)
	,IswResourceMobilization(IswResourceMobilization.class)
	,IswCostData(IswCostData.class)
	,IswIncidentResource(IswIncidentResource.class)
	,IswResourceOther(IswResourceOther.class)
	,IswIncidentResourceOther(IswIncidentResourceOther.class)
	,IswAirTravel(IswAirTravel.class)
	,IswWorkPeriod(IswWorkPeriod.class)
	,IswWorkPeriodOvernightStayInfo(IswWorkPeriodOvernightStayInfo.class)
	,IswWorkPeriodQuestionValue(IswWorkPeriodQuestionValue.class)
	,IswIncidentResourceDailyCost(IswIncidentResourceDailyCost.class)
	,IswAssignment(IswAssignment.class)
	,IswWorkPeriodAssignment(IswWorkPeriodAssignment.class)
	,IswAssignmentTime(IswAssignmentTime.class)
	,IswAdPaymentInfo(IswAdPaymentInfo.class)
	,IswContractorPaymentInfo(IswContractorPaymentInfo.class)
	,IswContractorRate(IswContractorRate.class)
	,IswContrPayinfoRate(IswContrPayinfoRate.class)
	,IswAssignmentTimePost(IswAssignmentTimePost.class)
	,IswTimeAssignAdjust(IswTimeAssignAdjust.class)
	,IswReport(IswReport.class)
	,IswTimeInvoice(IswTimeInvoice.class)
	,IswAssignmentTimePostInvoice(IswAssignmentTimePostInvoice.class)
	,IswTimeAssignAdjustInvoice(IswTimeAssignAdjustInvoice.class)
	,IswResourceInvoice(IswResourceInvoice.class)
	,IswCostAccrualExtract(IswCostAccrualExtract.class)
	,IswCostAccrualExtractRsc(IswCostAccrualExtractRsc.class)
	,IswProjection(IswProjection.class)
	,IswProjectionItem(IswProjectionItem.class)
	,IswProjectionItemWorksheet(IswProjectionItemWorksheet.class)
	,IswlComplexity(IswlComplexity.class)
	,IswlRecommendation(IswlRecommendation.class)
	,IswlFuelType(IswlFuelType.class)
	,IswlPriorityProgram(IswlPriorityProgram.class)
	,IswIncidentFuelType(IswIncidentFuelType.class)
	,IswResourceHomeUnitContact(IswResourceHomeUnitContact.class)
	,IswResourceTraining(IswResourceTraining.class)
	,IswRscTrainingFuelType(IswRscTrainingFuelType.class)
	,IswRscTrainingObjective(IswRscTrainingObjective.class)
	,IswRscTrainingTrainer(IswRscTrainingTrainer.class)
	,IswTrainingContact(IswTrainingContact.class)
	,IswTrainingSettings(IswTrainingSettings.class)
	,IswTrainingSetFuelType(IswTrainingSetFuelType.class)
;
    
	private Class tblClass;
	
	TableImportOrderEnum(Class cls){
		this.tblClass=cls;
	}

	public Class getTblClass() {
		return tblClass;
	}

}
