//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.29 at 03:00:43 PM MDT 
//


package gov.nwcg.isuite.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Used to express an Incident Resource.
 * 
 * <p>Java class for IncidentResourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentResourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Resource" type="{http://isuite.nwcg.gov/lib}ResourceType"/>
 *         &lt;element name="WorkPeriod" type="{http://isuite.nwcg.gov/lib}WorkPeriodType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentResourceType", propOrder = {
    "resource",
    "workPeriod"
})
public class IncidentResourceType {

    @XmlElement(name = "Resource", required = true)
    protected ResourceType resource;
    @XmlElement(name = "WorkPeriod", required = true)
    protected WorkPeriodType workPeriod;

    /**
     * Gets the value of the resource property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceType }
     *     
     */
    public ResourceType getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceType }
     *     
     */
    public void setResource(ResourceType value) {
        this.resource = value;
    }

    /**
     * Gets the value of the workPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link WorkPeriodType }
     *     
     */
    public WorkPeriodType getWorkPeriod() {
        return workPeriod;
    }

    /**
     * Sets the value of the workPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkPeriodType }
     *     
     */
    public void setWorkPeriod(WorkPeriodType value) {
        this.workPeriod = value;
    }

}
