//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.29 at 03:00:43 PM MDT 
//


package gov.nwcg.isuite.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nwcg.isuite.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nwcg.isuite.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IncidentType }
     * 
     */
    public IncidentType createIncidentType() {
        return new IncidentType();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link WorkPeriodType }
     * 
     */
    public WorkPeriodType createWorkPeriodType() {
        return new WorkPeriodType();
    }

    /**
     * Create an instance of {@link AssignmentType }
     * 
     */
    public AssignmentType createAssignmentType() {
        return new AssignmentType();
    }

    /**
     * Create an instance of {@link IncidentResourceType }
     * 
     */
    public IncidentResourceType createIncidentResourceType() {
        return new IncidentResourceType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link UserTransfer }
     * 
     */
    public UserTransfer createUserTransfer() {
        return new UserTransfer();
    }

}
