//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.29 at 03:00:43 PM MDT 
//


package gov.nwcg.isuite.xml;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for SystemRoleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SystemRoleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ROLE_ACCOUNT_MANAGER"/>
 *     &lt;enumeration value="ROLE_CHECKIN_DEMOB"/>
 *     &lt;enumeration value="ROLE_COST"/>
 *     &lt;enumeration value="ROLE_DATA_STEWARD"/>
 *     &lt;enumeration value="ROLE_IAP"/>
 *     &lt;enumeration value="ROLE_INJURY_ILLNESS"/>
 *     &lt;enumeration value="ROLE_SUPPLY_SUPERVISOR"/>
 *     &lt;enumeration value="ROLE_SUPPLY_CLERK"/>
 *     &lt;enumeration value="ROLE_SUPPLY_COMMUNICATIONS"/>
 *     &lt;enumeration value="ROLE_SYNC_MANAGER"/>
 *     &lt;enumeration value="ROLE_TIME"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum SystemRoleType {

    ROLE_ACCOUNT_MANAGER,
    ROLE_CHECKIN_DEMOB,
    ROLE_COST,
    ROLE_DATA_STEWARD,
    ROLE_IAP,
    ROLE_INJURY_ILLNESS,
    ROLE_SUPPLY_SUPERVISOR,
    ROLE_SUPPLY_CLERK,
    ROLE_SUPPLY_COMMUNICATIONS,
//    ROLE_SYNC_MANAGER,
    ROLE_SYSTEM,
    ROLE_TIME,
    ROLE_HELP_DESK,
    ROLE_GLOBAL_REF_DATA_MANAGER,
    ROLE_GEOGRAPHIC_DATA_MANAGER,
    ROLE_REPORT,
    ROLE_TRAINING_SPECIALIST;

    public String value() {
        return name();
    }

    public static SystemRoleType fromValue(String v) {
        return valueOf(v);
    }

}
