//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.23 at 04:41:59 PM MDT 
//


package gov.nwcg.isuite.xml.rossresource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Res_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Res_Disp_Org_Unit_Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Res_Prov_Unit_Code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Res_Prov_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Catalog_Item_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Update_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rowType", propOrder = {
    "resName",
    "resDispOrgUnitCode",
    "resProvUnitCode",
    "resProvName",
    "catalogItemName",
    "updateDate"
})
public class RowType {

    @XmlElement(name = "Res_ID", required = true)
    protected String resId;
    @XmlElement(name = "Res_Name", required = true)
    protected String resName;
    @XmlElement(name = "Res_Disp_Org_Unit_Code", required = true)
    protected String resDispOrgUnitCode;
    @XmlElement(name = "Res_Prov_Unit_Code", required = true)
    protected String resProvUnitCode;
    @XmlElement(name = "Res_Prov_Name", required = true)
    protected String resProvName;
    @XmlElement(name = "Catalog_Item_Name", required = true)
    protected String catalogItemName;
    @XmlElement(name = "Update_Date", required = true)
    protected String updateDate;

    /**
     * Gets the value of the resName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResName() {
        return resName;
    }

    /**
     * Sets the value of the resName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResName(String value) {
        this.resName = value;
    }

    /**
     * Gets the value of the resDispOrgUnitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResDispOrgUnitCode() {
        return resDispOrgUnitCode;
    }

    /**
     * Sets the value of the resDispOrgUnitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResDispOrgUnitCode(String value) {
        this.resDispOrgUnitCode = value;
    }

    /**
     * Gets the value of the resProvUnitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResProvUnitCode() {
        return resProvUnitCode;
    }

    /**
     * Sets the value of the resProvUnitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResProvUnitCode(String value) {
        this.resProvUnitCode = value;
    }

    /**
     * Gets the value of the resProvName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResProvName() {
        return resProvName;
    }

    /**
     * Sets the value of the resProvName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResProvName(String value) {
        this.resProvName = value;
    }

    /**
     * Gets the value of the catalogItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogItemName() {
        return catalogItemName;
    }

    /**
     * Sets the value of the catalogItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogItemName(String value) {
        this.catalogItemName = value;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateDate(String value) {
        this.updateDate = value;
    }

	public String getResId() {
		return resId;
	}

	public void setResId(String resId) {
		this.resId = resId;
	}

}
