//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 12:53:35 PM MDT 
//


package gov.nwcg.isuite.xml.financialexport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccrualsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccrualsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccrualHeaderID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CaptureDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CaptureTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PreparedByName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PreparedByPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Incidents" type="{http://isuite.nwcg.gov/FinancialExport}IncidentsType" maxOccurs="unbounded"/>
 *         &lt;element name="AccountingCodeSummary" type="{http://isuite.nwcg.gov/FinancialExport}AccountingCodeSummaryType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccrualsType", propOrder = {
    "accrualHeaderID",
    "captureDate",
    "captureTime",
    "preparedByName",
    "preparedByPhone",
    "incidents",
    "accountingCodeSummary"
})
public class AccrualsType {

    @XmlElement(name = "AccrualHeaderID")
    protected long accrualHeaderID;
    @XmlElement(name = "CaptureDate", required = true)
    protected String captureDate;
    @XmlElement(name = "CaptureTime", required = true)
    protected String captureTime;
    @XmlElement(name = "PreparedByName", required = true)
    protected String preparedByName;
    @XmlElement(name = "PreparedByPhone", required = true)
    protected String preparedByPhone;
    @XmlElement(name = "Incidents", required = true)
    protected List<IncidentsType> incidents;
    @XmlElement(name = "AccountingCodeSummary", required = true)
    protected List<AccountingCodeSummaryType> accountingCodeSummary;

    /**
     * Gets the value of the accrualHeaderID property.
     * 
     */
    public long getAccrualHeaderID() {
        return accrualHeaderID;
    }

    /**
     * Sets the value of the accrualHeaderID property.
     * 
     */
    public void setAccrualHeaderID(long value) {
        this.accrualHeaderID = value;
    }

    /**
     * Gets the value of the captureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptureDate() {
        return captureDate;
    }

    /**
     * Sets the value of the captureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptureDate(String value) {
        this.captureDate = value;
    }

    /**
     * Gets the value of the captureTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptureTime() {
        return captureTime;
    }

    /**
     * Sets the value of the captureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptureTime(String value) {
        this.captureTime = value;
    }

    /**
     * Gets the value of the preparedByName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreparedByName() {
        return preparedByName;
    }

    /**
     * Sets the value of the preparedByName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreparedByName(String value) {
        this.preparedByName = value;
    }

    /**
     * Gets the value of the preparedByPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreparedByPhone() {
        return preparedByPhone;
    }

    /**
     * Sets the value of the preparedByPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreparedByPhone(String value) {
        this.preparedByPhone = value;
    }

    /**
     * Gets the value of the incidents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentsType }
     * 
     * 
     */
    public List<IncidentsType> getIncidents() {
        if (incidents == null) {
            incidents = new ArrayList<IncidentsType>();
        }
        return this.incidents;
    }

    /**
     * Gets the value of the accountingCodeSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountingCodeSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountingCodeSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountingCodeSummaryType }
     * 
     * 
     */
    public List<AccountingCodeSummaryType> getAccountingCodeSummary() {
        if (accountingCodeSummary == null) {
            accountingCodeSummary = new ArrayList<AccountingCodeSummaryType>();
        }
        return this.accountingCodeSummary;
    }

}
