//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 12:53:35 PM MDT 
//


package gov.nwcg.isuite.xml.financialexport;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdjustmentSummary288Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdjustmentSummary288Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AdjustmentCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdjustmentAmountSummary" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="AdjustmentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdjustmentSummary288Type", propOrder = {
    "adjustmentCategory",
    "adjustmentAmountSummary",
    "adjustmentDate"
})
public class AdjustmentSummary288Type {

    @XmlElement(name = "AdjustmentCategory", required = true)
    protected String adjustmentCategory;
    @XmlElement(name = "AdjustmentAmountSummary", required = true)
    protected BigDecimal adjustmentAmountSummary;
    @XmlElement(name = "AdjustmentDate", required = true)
    protected String adjustmentDate;

    /**
     * Gets the value of the adjustmentCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjustmentCategory() {
        return adjustmentCategory;
    }

    /**
     * Sets the value of the adjustmentCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjustmentCategory(String value) {
        this.adjustmentCategory = value;
    }

    /**
     * Gets the value of the adjustmentAmountSummary property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdjustmentAmountSummary() {
        return adjustmentAmountSummary;
    }

    /**
     * Sets the value of the adjustmentAmountSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdjustmentAmountSummary(BigDecimal value) {
        this.adjustmentAmountSummary = value;
    }

    /**
     * Gets the value of the adjustmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjustmentDate() {
        return adjustmentDate;
    }

    /**
     * Sets the value of the adjustmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjustmentDate(String value) {
        this.adjustmentDate = value;
    }

}
