//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 12:53:35 PM MDT 
//


package gov.nwcg.isuite.xml.financialexport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Invoice288Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Invoice288Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ECI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PointOfHire" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdjustmentSummary288" type="{http://isuite.nwcg.gov/FinancialExport}AdjustmentSummary288Type" maxOccurs="unbounded"/>
 *         &lt;element name="PostingSummary288" type="{http://isuite.nwcg.gov/FinancialExport}PostingSummary288Type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Invoice288Type", propOrder = {
    "invoiceID",
    "invoiceNumber",
    "eci",
    "pointOfHire",
    "firstName",
    "lastName",
    "adjustmentSummary288",
    "postingSummary288"
})
public class Invoice288Type {

    @XmlElement(name = "InvoiceID", required = true)
    protected String invoiceID;
    @XmlElement(name = "InvoiceNumber", required = true)
    protected String invoiceNumber;
    @XmlElement(name = "ECI", required = true)
    protected String eci;
    @XmlElement(name = "PointOfHire", required = true)
    protected String pointOfHire;
    @XmlElement(name = "FirstName", required = true)
    protected String firstName;
    @XmlElement(name = "LastName", required = true)
    protected String lastName;
    @XmlElement(name = "AdjustmentSummary288", required = true)
    protected List<AdjustmentSummary288Type> adjustmentSummary288;
    @XmlElement(name = "PostingSummary288", required = true)
    protected List<PostingSummary288Type> postingSummary288;

    /**
     * Gets the value of the invoiceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceID() {
        return invoiceID;
    }

    /**
     * Sets the value of the invoiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceID(String value) {
        this.invoiceID = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the eci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECI() {
        return eci;
    }

    /**
     * Sets the value of the eci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECI(String value) {
        this.eci = value;
    }

    /**
     * Gets the value of the pointOfHire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointOfHire() {
        return pointOfHire;
    }

    /**
     * Sets the value of the pointOfHire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointOfHire(String value) {
        this.pointOfHire = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the adjustmentSummary288 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adjustmentSummary288 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjustmentSummary288().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdjustmentSummary288Type }
     * 
     * 
     */
    public List<AdjustmentSummary288Type> getAdjustmentSummary288() {
        if (adjustmentSummary288 == null) {
            adjustmentSummary288 = new ArrayList<AdjustmentSummary288Type>();
        }
        return this.adjustmentSummary288;
    }

    /**
     * Gets the value of the postingSummary288 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postingSummary288 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPostingSummary288().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PostingSummary288Type }
     * 
     * 
     */
    public List<PostingSummary288Type> getPostingSummary288() {
        if (postingSummary288 == null) {
            postingSummary288 = new ArrayList<PostingSummary288Type>();
        }
        return this.postingSummary288;
    }

}
