//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 12:53:35 PM MDT 
//


package gov.nwcg.isuite.xml.financialexport;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ISuiteInvoice286Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ISuiteInvoice286Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BeginDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OfficialNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InvoiceReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContractorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContractorAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContractorAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContractorCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContractorState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContractorZip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AgreementNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AgreementBegDt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AgreementExpDt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResourceKindDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UniqueName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Make" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PointOfHire" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HireDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HireTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdminOffice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdminOfficeAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdminOfficeAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdminOfficeCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdminOfficeState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AdminOfficeZip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GovtSuppliesYN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GovtOperatorYN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequestNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReleaseDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReleaseTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Withdrawn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TotalDeductions" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="TotalAdditions" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="AdjustmentDetail286" type="{http://isuite.nwcg.gov/FinancialExport}AdjustmentDetail286Type" maxOccurs="unbounded"/>
 *         &lt;element name="Invoice286" type="{http://isuite.nwcg.gov/FinancialExport}Invoice286Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ISuiteInvoice286Type", propOrder = {
    "invoiceID",
    "beginDate",
    "endDate",
    "officialNum",
    "invoiceReason",
    "contractorName",
    "contractorAddress1",
    "contractorAddress2",
    "contractorCity",
    "contractorState",
    "contractorZip",
    "agreementNum",
    "agreementBegDt",
    "agreementExpDt",
    "resourceKindDescription",
    "uniqueName",
    "make",
    "model",
    "pointOfHire",
    "hireDate",
    "hireTime",
    "adminOffice",
    "adminOfficeAddress1",
    "adminOfficeAddress2",
    "adminOfficeCity",
    "adminOfficeState",
    "adminOfficeZip",
    "govtSuppliesYN",
    "govtOperatorYN",
    "requestNumber",
    "releaseDate",
    "releaseTime",
    "withdrawn",
    "remarks",
    "totalDeductions",
    "totalAdditions",
    "adjustmentDetail286",
    "invoice286"
})
public class ISuiteInvoice286Type {

    @XmlElement(name = "InvoiceID", required = true)
    protected String invoiceID;
    @XmlElement(name = "BeginDate", required = true)
    protected String beginDate;
    @XmlElement(name = "EndDate", required = true)
    protected String endDate;
    @XmlElement(name = "OfficialNum", required = true)
    protected String officialNum;
    @XmlElement(name = "InvoiceReason", required = true)
    protected String invoiceReason;
    @XmlElement(name = "ContractorName", required = true)
    protected String contractorName;
    @XmlElement(name = "ContractorAddress1", required = true)
    protected String contractorAddress1;
    @XmlElement(name = "ContractorAddress2", required = true)
    protected String contractorAddress2;
    @XmlElement(name = "ContractorCity", required = true)
    protected String contractorCity;
    @XmlElement(name = "ContractorState", required = true)
    protected String contractorState;
    @XmlElement(name = "ContractorZip", required = true)
    protected String contractorZip;
    @XmlElement(name = "AgreementNum", required = true)
    protected String agreementNum;
    @XmlElement(name = "AgreementBegDt", required = true)
    protected String agreementBegDt;
    @XmlElement(name = "AgreementExpDt", required = true)
    protected String agreementExpDt;
    @XmlElement(name = "ResourceKindDescription", required = true)
    protected String resourceKindDescription;
    @XmlElement(name = "UniqueName", required = true)
    protected String uniqueName;
    @XmlElement(name = "Make", required = true)
    protected String make;
    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "PointOfHire", required = true)
    protected String pointOfHire;
    @XmlElement(name = "HireDate", required = true)
    protected String hireDate;
    @XmlElement(name = "HireTime", required = true)
    protected String hireTime;
    @XmlElement(name = "AdminOffice", required = true)
    protected String adminOffice;
    @XmlElement(name = "AdminOfficeAddress1", required = true)
    protected String adminOfficeAddress1;
    @XmlElement(name = "AdminOfficeAddress2", required = true)
    protected String adminOfficeAddress2;
    @XmlElement(name = "AdminOfficeCity", required = true)
    protected String adminOfficeCity;
    @XmlElement(name = "AdminOfficeState", required = true)
    protected String adminOfficeState;
    @XmlElement(name = "AdminOfficeZip", required = true)
    protected String adminOfficeZip;
    @XmlElement(name = "GovtSuppliesYN", required = true)
    protected String govtSuppliesYN;
    @XmlElement(name = "GovtOperatorYN", required = true)
    protected String govtOperatorYN;
    @XmlElement(name = "RequestNumber", required = true)
    protected String requestNumber;
    @XmlElement(name = "ReleaseDate", required = true)
    protected String releaseDate;
    @XmlElement(name = "ReleaseTime", required = true)
    protected String releaseTime;
    @XmlElement(name = "Withdrawn", required = true)
    protected String withdrawn;
    @XmlElement(name = "Remarks", required = true)
    protected String remarks;
    @XmlElement(name = "TotalDeductions", required = true)
    protected BigDecimal totalDeductions;
    @XmlElement(name = "TotalAdditions", required = true)
    protected BigDecimal totalAdditions;
    @XmlElement(name = "AdjustmentDetail286", required = true)
    protected List<AdjustmentDetail286Type> adjustmentDetail286;
    @XmlElement(name = "Invoice286", required = true)
    protected Invoice286Type invoice286;

    /**
     * Gets the value of the invoiceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceID() {
        return invoiceID;
    }

    /**
     * Sets the value of the invoiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceID(String value) {
        this.invoiceID = value;
    }

    /**
     * Gets the value of the beginDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * Sets the value of the beginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeginDate(String value) {
        this.beginDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the officialNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficialNum() {
        return officialNum;
    }

    /**
     * Sets the value of the officialNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficialNum(String value) {
        this.officialNum = value;
    }

    /**
     * Gets the value of the invoiceReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceReason() {
        return invoiceReason;
    }

    /**
     * Sets the value of the invoiceReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceReason(String value) {
        this.invoiceReason = value;
    }

    /**
     * Gets the value of the contractorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractorName() {
        return contractorName;
    }

    /**
     * Sets the value of the contractorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractorName(String value) {
        this.contractorName = value;
    }

    /**
     * Gets the value of the contractorAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractorAddress1() {
        return contractorAddress1;
    }

    /**
     * Sets the value of the contractorAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractorAddress1(String value) {
        this.contractorAddress1 = value;
    }

    /**
     * Gets the value of the contractorAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractorAddress2() {
        return contractorAddress2;
    }

    /**
     * Sets the value of the contractorAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractorAddress2(String value) {
        this.contractorAddress2 = value;
    }

    /**
     * Gets the value of the contractorCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractorCity() {
        return contractorCity;
    }

    /**
     * Sets the value of the contractorCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractorCity(String value) {
        this.contractorCity = value;
    }

    /**
     * Gets the value of the contractorState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractorState() {
        return contractorState;
    }

    /**
     * Sets the value of the contractorState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractorState(String value) {
        this.contractorState = value;
    }

    /**
     * Gets the value of the contractorZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractorZip() {
        return contractorZip;
    }

    /**
     * Sets the value of the contractorZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractorZip(String value) {
        this.contractorZip = value;
    }

    /**
     * Gets the value of the agreementNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementNum() {
        return agreementNum;
    }

    /**
     * Sets the value of the agreementNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementNum(String value) {
        this.agreementNum = value;
    }

    /**
     * Gets the value of the agreementBegDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementBegDt() {
        return agreementBegDt;
    }

    /**
     * Sets the value of the agreementBegDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementBegDt(String value) {
        this.agreementBegDt = value;
    }

    /**
     * Gets the value of the agreementExpDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementExpDt() {
        return agreementExpDt;
    }

    /**
     * Sets the value of the agreementExpDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementExpDt(String value) {
        this.agreementExpDt = value;
    }

    /**
     * Gets the value of the resourceKindDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceKindDescription() {
        return resourceKindDescription;
    }

    /**
     * Sets the value of the resourceKindDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceKindDescription(String value) {
        this.resourceKindDescription = value;
    }

    /**
     * Gets the value of the uniqueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueName() {
        return uniqueName;
    }

    /**
     * Sets the value of the uniqueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueName(String value) {
        this.uniqueName = value;
    }

    /**
     * Gets the value of the make property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMake() {
        return make;
    }

    /**
     * Sets the value of the make property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMake(String value) {
        this.make = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the pointOfHire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointOfHire() {
        return pointOfHire;
    }

    /**
     * Sets the value of the pointOfHire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointOfHire(String value) {
        this.pointOfHire = value;
    }

    /**
     * Gets the value of the hireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHireDate() {
        return hireDate;
    }

    /**
     * Sets the value of the hireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHireDate(String value) {
        this.hireDate = value;
    }

    /**
     * Gets the value of the hireTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHireTime() {
        return hireTime;
    }

    /**
     * Sets the value of the hireTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHireTime(String value) {
        this.hireTime = value;
    }

    /**
     * Gets the value of the adminOffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminOffice() {
        return adminOffice;
    }

    /**
     * Sets the value of the adminOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminOffice(String value) {
        this.adminOffice = value;
    }

    /**
     * Gets the value of the adminOfficeAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminOfficeAddress1() {
        return adminOfficeAddress1;
    }

    /**
     * Sets the value of the adminOfficeAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminOfficeAddress1(String value) {
        this.adminOfficeAddress1 = value;
    }

    /**
     * Gets the value of the adminOfficeAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminOfficeAddress2() {
        return adminOfficeAddress2;
    }

    /**
     * Sets the value of the adminOfficeAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminOfficeAddress2(String value) {
        this.adminOfficeAddress2 = value;
    }

    /**
     * Gets the value of the adminOfficeCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminOfficeCity() {
        return adminOfficeCity;
    }

    /**
     * Sets the value of the adminOfficeCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminOfficeCity(String value) {
        this.adminOfficeCity = value;
    }

    /**
     * Gets the value of the adminOfficeState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminOfficeState() {
        return adminOfficeState;
    }

    /**
     * Sets the value of the adminOfficeState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminOfficeState(String value) {
        this.adminOfficeState = value;
    }

    /**
     * Gets the value of the adminOfficeZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdminOfficeZip() {
        return adminOfficeZip;
    }

    /**
     * Sets the value of the adminOfficeZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdminOfficeZip(String value) {
        this.adminOfficeZip = value;
    }

    /**
     * Gets the value of the govtSuppliesYN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovtSuppliesYN() {
        return govtSuppliesYN;
    }

    /**
     * Sets the value of the govtSuppliesYN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovtSuppliesYN(String value) {
        this.govtSuppliesYN = value;
    }

    /**
     * Gets the value of the govtOperatorYN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovtOperatorYN() {
        return govtOperatorYN;
    }

    /**
     * Sets the value of the govtOperatorYN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovtOperatorYN(String value) {
        this.govtOperatorYN = value;
    }

    /**
     * Gets the value of the requestNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestNumber() {
        return requestNumber;
    }

    /**
     * Sets the value of the requestNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestNumber(String value) {
        this.requestNumber = value;
    }

    /**
     * Gets the value of the releaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseDate() {
        return releaseDate;
    }

    /**
     * Sets the value of the releaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseDate(String value) {
        this.releaseDate = value;
    }

    /**
     * Gets the value of the releaseTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseTime() {
        return releaseTime;
    }

    /**
     * Sets the value of the releaseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseTime(String value) {
        this.releaseTime = value;
    }

    /**
     * Gets the value of the withdrawn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWithdrawn() {
        return withdrawn;
    }

    /**
     * Sets the value of the withdrawn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWithdrawn(String value) {
        this.withdrawn = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the totalDeductions property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalDeductions() {
        return totalDeductions;
    }

    /**
     * Sets the value of the totalDeductions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalDeductions(BigDecimal value) {
        this.totalDeductions = value;
    }

    /**
     * Gets the value of the totalAdditions property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAdditions() {
        return totalAdditions;
    }

    /**
     * Sets the value of the totalAdditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAdditions(BigDecimal value) {
        this.totalAdditions = value;
    }

    /**
     * Gets the value of the adjustmentDetail286 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adjustmentDetail286 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjustmentDetail286().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdjustmentDetail286Type }
     * 
     * 
     */
    public List<AdjustmentDetail286Type> getAdjustmentDetail286() {
        if (adjustmentDetail286 == null) {
            adjustmentDetail286 = new ArrayList<AdjustmentDetail286Type>();
        }
        return this.adjustmentDetail286;
    }

    /**
     * Gets the value of the invoice286 property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice286Type }
     *     
     */
    public Invoice286Type getInvoice286() {
        return invoice286;
    }

    /**
     * Sets the value of the invoice286 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice286Type }
     *     
     */
    public void setInvoice286(Invoice286Type value) {
        this.invoice286 = value;
    }

}
