//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 12:53:35 PM MDT 
//


package gov.nwcg.isuite.xml.financialexport;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nwcg.isuite.xml.financialexport package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nwcg.isuite.xml.financialexport
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ISuiteExport }
     * 
     */
    public ISuiteExport createISuiteExport() {
        return new ISuiteExport();
    }

    /**
     * Create an instance of {@link DBIncidentsType }
     * 
     */
    public DBIncidentsType createDBIncidentsType() {
        return new DBIncidentsType();
    }

    /**
     * Create an instance of {@link AccrualsType }
     * 
     */
    public AccrualsType createAccrualsType() {
        return new AccrualsType();
    }

    /**
     * Create an instance of {@link ISuiteInvoice286Type }
     * 
     */
    public ISuiteInvoice286Type createISuiteInvoice286Type() {
        return new ISuiteInvoice286Type();
    }

    /**
     * Create an instance of {@link Invoice288Type }
     * 
     */
    public Invoice288Type createInvoice288Type() {
        return new Invoice288Type();
    }

    /**
     * Create an instance of {@link AcctCodeSummary286Type }
     * 
     */
    public AcctCodeSummary286Type createAcctCodeSummary286Type() {
        return new AcctCodeSummary286Type();
    }

    /**
     * Create an instance of {@link PostingSummary286Type }
     * 
     */
    public PostingSummary286Type createPostingSummary286Type() {
        return new PostingSummary286Type();
    }

    /**
     * Create an instance of {@link PostingSummary288Type }
     * 
     */
    public PostingSummary288Type createPostingSummary288Type() {
        return new PostingSummary288Type();
    }

    /**
     * Create an instance of {@link AdjustmentDetail286Type }
     * 
     */
    public AdjustmentDetail286Type createAdjustmentDetail286Type() {
        return new AdjustmentDetail286Type();
    }

    /**
     * Create an instance of {@link AdjustmentSummary288Type }
     * 
     */
    public AdjustmentSummary288Type createAdjustmentSummary288Type() {
        return new AdjustmentSummary288Type();
    }

    /**
     * Create an instance of {@link PostingDetail286Type }
     * 
     */
    public PostingDetail286Type createPostingDetail286Type() {
        return new PostingDetail286Type();
    }

    /**
     * Create an instance of {@link PostingDetail288Type }
     * 
     */
    public PostingDetail288Type createPostingDetail288Type() {
        return new PostingDetail288Type();
    }

    /**
     * Create an instance of {@link AccrualDetailType }
     * 
     */
    public AccrualDetailType createAccrualDetailType() {
        return new AccrualDetailType();
    }

    /**
     * Create an instance of {@link IncidentsType }
     * 
     */
    public IncidentsType createIncidentsType() {
        return new IncidentsType();
    }

    /**
     * Create an instance of {@link RCLineSummaryType }
     * 
     */
    public RCLineSummaryType createRCLineSummaryType() {
        return new RCLineSummaryType();
    }

    /**
     * Create an instance of {@link Invoice286Type }
     * 
     */
    public Invoice286Type createInvoice286Type() {
        return new Invoice286Type();
    }

    /**
     * Create an instance of {@link AccountingCodeSummaryType }
     * 
     */
    public AccountingCodeSummaryType createAccountingCodeSummaryType() {
        return new AccountingCodeSummaryType();
    }

}
