//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 12:53:35 PM MDT 
//


package gov.nwcg.isuite.xml.financialexport;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostingDetail286Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostingDetail286Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfUnits" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Rate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="SStartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SStopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SNumberOfUnits" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SUnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="SAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Guarantee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostingDetail286Type", propOrder = {
    "startTime",
    "stopTime",
    "numberOfUnits",
    "unitOfMeasure",
    "rate",
    "amount",
    "sStartTime",
    "sStopTime",
    "sNumberOfUnits",
    "sUnitOfMeasure",
    "sRate",
    "sAmount",
    "guarantee"
})
public class PostingDetail286Type {

    @XmlElement(name = "StartTime", required = true)
    protected String startTime;
    @XmlElement(name = "StopTime", required = true)
    protected String stopTime;
    @XmlElement(name = "NumberOfUnits", required = true)
    protected String numberOfUnits;
    @XmlElement(name = "UnitOfMeasure", required = true)
    protected String unitOfMeasure;
    @XmlElement(name = "Rate", required = true)
    protected BigDecimal rate;
    @XmlElement(name = "Amount", required = true)
    protected BigDecimal amount;
    @XmlElement(name = "SStartTime", required = true)
    protected String sStartTime;
    @XmlElement(name = "SStopTime", required = true)
    protected String sStopTime;
    @XmlElement(name = "SNumberOfUnits", required = true)
    protected String sNumberOfUnits;
    @XmlElement(name = "SUnitOfMeasure", required = true)
    protected String sUnitOfMeasure;
    @XmlElement(name = "SRate", required = true)
    protected BigDecimal sRate;
    @XmlElement(name = "SAmount", required = true)
    protected BigDecimal sAmount;
    @XmlElement(name = "Guarantee", required = true)
    protected BigDecimal guarantee;

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the stopTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopTime() {
        return stopTime;
    }

    /**
     * Sets the value of the stopTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopTime(String value) {
        this.stopTime = value;
    }

    /**
     * Gets the value of the numberOfUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfUnits() {
        return numberOfUnits;
    }

    /**
     * Sets the value of the numberOfUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfUnits(String value) {
        this.numberOfUnits = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRate(BigDecimal value) {
        this.rate = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the sStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSStartTime() {
        return sStartTime;
    }

    /**
     * Sets the value of the sStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSStartTime(String value) {
        this.sStartTime = value;
    }

    /**
     * Gets the value of the sStopTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSStopTime() {
        return sStopTime;
    }

    /**
     * Sets the value of the sStopTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSStopTime(String value) {
        this.sStopTime = value;
    }

    /**
     * Gets the value of the sNumberOfUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNumberOfUnits() {
        return sNumberOfUnits;
    }

    /**
     * Sets the value of the sNumberOfUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNumberOfUnits(String value) {
        this.sNumberOfUnits = value;
    }

    /**
     * Gets the value of the sUnitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUnitOfMeasure() {
        return sUnitOfMeasure;
    }

    /**
     * Sets the value of the sUnitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUnitOfMeasure(String value) {
        this.sUnitOfMeasure = value;
    }

    /**
     * Gets the value of the sRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSRate() {
        return sRate;
    }

    /**
     * Sets the value of the sRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSRate(BigDecimal value) {
        this.sRate = value;
    }

    /**
     * Gets the value of the sAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSAmount() {
        return sAmount;
    }

    /**
     * Sets the value of the sAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSAmount(BigDecimal value) {
        this.sAmount = value;
    }

    /**
     * Gets the value of the guarantee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuarantee() {
        return guarantee;
    }

    /**
     * Sets the value of the guarantee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuarantee(BigDecimal value) {
        this.guarantee = value;
    }

}
