//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 12:53:35 PM MDT 
//


package gov.nwcg.isuite.xml.financialexport;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostingSummary286Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostingSummary286Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TotalAmountEarned" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Guarantee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="PostTotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ActivityDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PostingDetail286" type="{http://isuite.nwcg.gov/FinancialExport}PostingDetail286Type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostingSummary286Type", propOrder = {
    "totalAmountEarned",
    "guarantee",
    "postTotal",
    "activityDate",
    "postingDetail286"
})
public class PostingSummary286Type {

    @XmlElement(name = "TotalAmountEarned", required = true)
    protected BigDecimal totalAmountEarned;
    @XmlElement(name = "Guarantee", required = true)
    protected BigDecimal guarantee;
    @XmlElement(name = "PostTotal", required = true)
    protected BigDecimal postTotal;
    @XmlElement(name = "ActivityDate", required = true)
    protected String activityDate;
    @XmlElement(name = "PostingDetail286", required = true)
    protected List<PostingDetail286Type> postingDetail286;

    /**
     * Gets the value of the totalAmountEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAmountEarned() {
        return totalAmountEarned;
    }

    /**
     * Sets the value of the totalAmountEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAmountEarned(BigDecimal value) {
        this.totalAmountEarned = value;
    }

    /**
     * Gets the value of the guarantee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGuarantee() {
        return guarantee;
    }

    /**
     * Sets the value of the guarantee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGuarantee(BigDecimal value) {
        this.guarantee = value;
    }

    /**
     * Gets the value of the postTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPostTotal() {
        return postTotal;
    }

    /**
     * Sets the value of the postTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPostTotal(BigDecimal value) {
        this.postTotal = value;
    }

    /**
     * Gets the value of the activityDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityDate() {
        return activityDate;
    }

    /**
     * Sets the value of the activityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityDate(String value) {
        this.activityDate = value;
    }

    /**
     * Gets the value of the postingDetail286 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postingDetail286 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPostingDetail286().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PostingDetail286Type }
     * 
     * 
     */
    public List<PostingDetail286Type> getPostingDetail286() {
        if (postingDetail286 == null) {
            postingDetail286 = new ArrayList<PostingDetail286Type>();
        }
        return this.postingDetail286;
    }

}
