//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 12:53:35 PM MDT 
//


package gov.nwcg.isuite.xml.financialexport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PostingDetail288Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostingDetail288Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActivityDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SpecialPayCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ColumnNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostingDetail288Type", propOrder = {
    "activityDate",
    "startTime",
    "stopTime",
    "specialPayCode",
    "reportOrder",
    "columnNumber"
})
public class PostingDetail288Type {

    @XmlElement(name = "ActivityDate", required = true)
    protected String activityDate;
    @XmlElement(name = "StartTime", required = true)
    protected String startTime;
    @XmlElement(name = "StopTime", required = true)
    protected String stopTime;
    @XmlElement(name = "SpecialPayCode", required = true)
    protected String specialPayCode;
    @XmlElement(name = "ReportOrder", required = true)
    protected String reportOrder;
    @XmlElement(name = "ColumnNumber", required = true)
    protected String columnNumber;

    /**
     * Gets the value of the activityDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityDate() {
        return activityDate;
    }

    /**
     * Sets the value of the activityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityDate(String value) {
        this.activityDate = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the stopTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopTime() {
        return stopTime;
    }

    /**
     * Sets the value of the stopTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopTime(String value) {
        this.stopTime = value;
    }

    /**
     * Gets the value of the specialPayCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialPayCode() {
        return specialPayCode;
    }

    /**
     * Sets the value of the specialPayCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialPayCode(String value) {
        this.specialPayCode = value;
    }

    /**
     * Gets the value of the reportOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportOrder() {
        return reportOrder;
    }

    /**
     * Sets the value of the reportOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportOrder(String value) {
        this.reportOrder = value;
    }

    /**
     * Gets the value of the columnNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnNumber() {
        return columnNumber;
    }

    /**
     * Sets the value of the columnNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnNumber(String value) {
        this.columnNumber = value;
    }

}
