//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 02:41:46 PM MDT 
//


package gov.nwcg.isuite.xml.ross;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for itemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="itemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="xs:ENTITIES"/>
 *             &lt;enumeration value="xs:ENTITY"/>
 *             &lt;enumeration value="xs:ID"/>
 *             &lt;enumeration value="xs:IDREF"/>
 *             &lt;enumeration value="xs:IDREFS"/>
 *             &lt;enumeration value="xs:NCName"/>
 *             &lt;enumeration value="xs:NMTOKEN"/>
 *             &lt;enumeration value="xs:NMTOKENS"/>
 *             &lt;enumeration value="xs:NOTATION"/>
 *             &lt;enumeration value="xs:Name"/>
 *             &lt;enumeration value="xs:QName"/>
 *             &lt;enumeration value="xs:anyURI"/>
 *             &lt;enumeration value="xs:base64Binary"/>
 *             &lt;enumeration value="xs:boolean"/>
 *             &lt;enumeration value="xs:byte"/>
 *             &lt;enumeration value="xs:date"/>
 *             &lt;enumeration value="xs:dateTime"/>
 *             &lt;enumeration value="xs:decimal"/>
 *             &lt;enumeration value="xs:double"/>
 *             &lt;enumeration value="xs:duration"/>
 *             &lt;enumeration value="xs:float"/>
 *             &lt;enumeration value="xs:gDay"/>
 *             &lt;enumeration value="xs:gMonth"/>
 *             &lt;enumeration value="xs:gMonthDay"/>
 *             &lt;enumeration value="xs:gYear"/>
 *             &lt;enumeration value="xs:gYearMonth"/>
 *             &lt;enumeration value="xs:hexBinary"/>
 *             &lt;enumeration value="xs:int"/>
 *             &lt;enumeration value="xs:integer"/>
 *             &lt;enumeration value="xs:language"/>
 *             &lt;enumeration value="xs:long"/>
 *             &lt;enumeration value="xs:negativeInteger"/>
 *             &lt;enumeration value="xs:nonNegativeInteger"/>
 *             &lt;enumeration value="xs:nonPositiveInteger"/>
 *             &lt;enumeration value="xs:normalizedString"/>
 *             &lt;enumeration value="xs:positiveInteger"/>
 *             &lt;enumeration value="xs:short"/>
 *             &lt;enumeration value="xs:string"/>
 *             &lt;enumeration value="xs:time"/>
 *             &lt;enumeration value="xs:token"/>
 *             &lt;enumeration value="xs:unsignedByte"/>
 *             &lt;enumeration value="xs:unsignedInt"/>
 *             &lt;enumeration value="xs:unsignedLong"/>
 *             &lt;enumeration value="xs:unsignedShort"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="precision" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemType")
public class ItemType {

    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "length")
    protected Integer length;
    @XmlAttribute(name = "scale")
    protected Integer scale;
    @XmlAttribute(name = "precision")
    protected Integer precision;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLength(Integer value) {
        this.length = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScale(Integer value) {
        this.scale = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrecision(Integer value) {
        this.precision = value;
    }

}
