//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 02:41:46 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://developer.cognos.com/schemas/xmldata/1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.nwcg.isuite.xml.ross;
